### ISSUE TITLE
The data is restored to the new database, and the schema information is not completely updated.

### ISSUE THREAD

**Issue by tongtongyin** [pingcap/br#1002]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
A normal full recovery, Although the data can be restored to the target database, but if you use SQL statements SELECT TABLE_SCHEMA, SUM(DATA_LENGTH) FROM TABLES GROUP BY TABLE_SCHEMA in information_schema database. Then you will find that the restored database size is still 0.

2. What did you expect to see?
The size of the restored database should be equal to the size of the backed up database.

3. What did you see instead?
the restored database size is still 0.

4. What version of BR and TiDB/TiKV/PD are you using?

5. Operation logs
   - Please upload `br.log` for BR if possible
   - Please upload `tidb-lightning.log` for TiDB-Lightning if possible
   - Please upload `tikv-importer.log` from TiKV-Importer if possible
   - Other interesting logs

6. Configuration of the cluster and the task
   - `tidb-lightning.toml` for TiDB-Lightning if possible
   - `tikv-importer.toml` for TiKV-Importer if possible
   - `topology.yml` if deployed by TiUP

7. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus if possible

**Comment by cyliu0** [comment]
This is a [FAQ](https://docs.pingcap.com/tidb/stable/backup-and-restore-faq#after-br-restores-the-backup-data-do-i-need-to-execute-the-analyze-statement-on-the-table-to-update-the-statistics-of-tidb-on-the-tables-and-indexes). You need to analyze the tables manually after restore. We had a discussion about adding analyze after restore. Do we have an actual plan to support this in the future? @overvenus @3pointer @IANTHEREAL

**Comment by kennytm** [comment]
@cyliu0 #679
