### ISSUE TITLE
When backing up an empty cluster, nothing will be output.

### ISSUE THREAD

**Issue by tongtongyin** [pingcap/br#1016]
Please answer these questions before submitting your issue. Thanks!!
1. What did you do?
When backing up an empty cluster, nothing will be output.It will not show that the backup is complete, nor will it show an error.

2. What did you expect to see?
Similar to a summary ：["Full backup Failed summary: total backup ranges: 0, total success: 0, total failed: 0"] [BackupTS=xxxxxxxxxxxxxxxxxx]

3. What did you see instead?
Nothing at all

4. What version of BR and TiDB/TiKV/PD are you using?

5. Operation logs
command：
<img width="1264" alt="command" src="https://user-images.githubusercontent.com/37565148/114827292-120b1380-9dfb-11eb-86a3-c988eb0fefff.png">

brlog：
<img width="2544" alt="log" src="https://user-images.githubusercontent.com/37565148/114826674-5a760180-9dfa-11eb-9a72-6f3867fff825.png">

6. Configuration of the cluster and the task
   - `tidb-lightning.toml` for TiDB-Lightning if possible
   - `tikv-importer.toml` for TiKV-Importer if possible
   - `topology.yml` if deployed by TiUP

7. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus if possible

**Comment by kennytm** [comment]
please see #828 about backing up empty database.

**Comment by YuJuncen** [comment]
Uh, seems the failure summary was putted with `log.Info`, which record logs to log file only.

https://github.com/pingcap/br/blob/31e539ce3824985f79e5ca508bea00a9d9bc52c4/pkg/summary/collector.go#L187-L191

Let me fix it...
