### ISSUE TITLE
Lightning should raise error immediately w/o valid s3 credentials

### ISSUE THREAD

**Issue by cyliu0** [pingcap/br#1041]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
Lightning import data without valid s3 credentials

2. What did you expect to see?
Raise error immediately

3. What did you see instead?
Lightning retried several times and raised error after more than 2 mins

4. What version of BR and TiDB/TiKV/PD are you using?

```
$ bin/tidb-lightning -V
Release Version: v5.0.0-14-gb3bd5495
Git Commit Hash: b3bd5495369244cfb1d3f2c49763a7fdb55d4ecd
Git Branch: release-5.0
Go Version: go1.16.3
UTC Build Time: 2021-04-20 07:46:20
Race Enabled: false
```

5. Operation logs
   - Please upload `br.log` for BR if possible
   - Please upload `tidb-lightning.log` for TiDB-Lightning if possible
     - [tidb-lightning.log](https://github.com/pingcap/br/files/6342246/tidb-lightning.log)
   - Please upload `tikv-importer.log` from TiKV-Importer if possible
   - Other interesting logs

6. Configuration of the cluster and the task
   - `tidb-lightning.toml` for TiDB-Lightning if possible
   - `tikv-importer.toml` for TiKV-Importer if possible
   - `topology.yml` if deployed by TiUP

7. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus if possible

**Comment by glorv** [comment]
So we should exclude errors that are obviously unretryable. @YuJuncen PTAL

**Comment by kennytm** [comment]
(#642 is relevant)

**Comment by sleepymole** [comment]
It should be fixed by https://github.com/pingcap/tidb/pull/33794.
