### ISSUE TITLE
Upgrade Go version to 1.16

### ISSUE THREAD

**Issue by tisonkun** [pingcap/br#1102]
## Development Task

So far, BR development uses Go 1.13 which is end of life for a while. Also for supporting running on Apple M1 silicon, it is required to upgrade to 1.16.

@CadmusJiang and @zhouqiang-cl are in charge for upgrading Go version to 1.16 and most of validation works are done manually. Hopefully we get it done in this month.

This also supports TiDB stacks to upgrade Go version to 1.16 https://github.com/pingcap/tidb/issues/22198

Related tasks

- https://github.com/pingcap/br/issues/1034

**Comment by kennytm** [comment]
closed by #1159.
