### ISSUE TITLE
lightning tidb backend failed when tidb auto commit is not enabled

### ISSUE THREAD

**Issue by glorv** [pingcap/br#1104]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
Use lightning tidb backend to load data into tidb who's `auto-commit` is disabled by default.

2. What did you expect to see?
Import should succeed.

3. What did you see instead?
Lightning failed with following error message:
```
[error="restore table `db`.`table` failed"] [error="Error 8004: transaction too large, len: 300001"]
```

**Comment by SunRunAway** [comment]
Why this bug is moderate? 

It should be critical because the functionality can not work in this situation.
