### ISSUE TITLE
The backup cpu resource is restricted

### ISSUE THREAD

**Issue by jacktd9** [pingcap/br#1118]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
 ./br backup full --pd "172.16.4.51:4779"   --storage "local:///data2/br_full" --ratelimit 50 --concurrency 4 --log-file backuptable.log

2. What did you expect to see?
cpu 使用率未受到限制

3. What did you see instead?
备份时 cpu 使用率未受到限制，主机 cpu 资源消耗超过 75%，如果产线环境执行备份过于危险，影响线上业务。
了解到 backup.num-threads 控制目标的备份的有效线程，但初始值 cpu 75%，过于大了吧，它能动态修改，是否可以备份时代入这个值传给目标用于限制 cpu 的使用消耗，或者其他方式规避资源的消耗
![image](https://user-images.githubusercontent.com/63033738/118466595-953ec280-b735-11eb-8270-740866d021e7.png)

![image](https://user-images.githubusercontent.com/63033738/118466335-5872cb80-b735-11eb-8ab5-26e152cf1070.png)

4. What version of BR and TiDB/TiKV/PD are you using?
v4.0.10 ~ v4.0.12

5. Operation logs
   - Please upload `br.log` for BR if possible
   - Please upload `tidb-lightning.log` for TiDB-Lightning if possible
   - Please upload `tikv-importer.log` from TiKV-Importer if possible
   - Other interesting logs

6. Configuration of the cluster and the task
   - `tidb-lightning.toml` for TiDB-Lightning if possible
   - `tikv-importer.toml` for TiKV-Importer if possible
   - `topology.yml` if deployed by TiUP

7. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus if possible

**Comment by 3pointer** [comment]
Actually, it's not a bug.  it's by design. you can find the details at this PR https://github.com/tikv/tikv/pull/8193

**Comment by jacktd9** [comment]
Okay, actually ,what I want to express is how to limit the usage of cpu, because this is very important for use in a production environment, but there are no instructions on the num-threads document. If you follow the default posture, it is likely to affect online work.

**Comment by cyliu0** [comment]
@jacktd9 You may refer to [backup.num-threads](https://docs.pingcap.com/zh/tidb/stable/tikv-configuration-file#backup) on the tikv side. You could configure this in the configuration file or change it by [Modify Configuration Online](https://docs.pingcap.com/zh/tidb/stable/dynamic-config#%E5%9C%A8%E7%BA%BF%E4%BF%AE%E6%94%B9-tikv-%E9%85%8D%E7%BD%AE)
