### ISSUE TITLE
BR tool get backup data stream

### ISSUE THREAD

**Issue by banyintian** [pingcap/br#1147]
## Question
Now I have a requirement, I want to obtain the backup data stream through BR tool , not just the backup metadata information.
Can I achieve this by modifying br source code?

**Comment by zwj-coder** [comment]
Can you clarify you requirement or any background? like you want to backup data or merely backup metadata through streaming?

**Comment by banyintian** [comment]
I want to make a full backup and incremental backup program, and find that BR tool meets the requirements, but br can't directly obtain the data stream of tidb backup, so I want to know whether tidb can directly send the backup data stream to br tool? Storage work in BR to do!













在 2021-05-28 13:24:55，"zhangwenjum" ***@***.***> 写道：

Can you clarify you requirement or any background? like you want to backup data or merely backup metadata through streaming?

**Comment by zwj-coder** [comment]
If you want to get a data stream from BR, it's unrealistic, because BR is only a tool to schedule and distribute the backup data to specified storage. The backup data is stored as a key-value format in TiKV and BR can not parse the backup data.
