### ISSUE TITLE
master branch CI always failed

### ISSUE THREAD

**Issue by tisonkun** [pingcap/br#1167]
https://github.com/pingcap/br/commits/master

It looks like a GitHub Actions wrong config. [report](https://github.com/pingcap/br/runs/2431571784)

**Comment by tisonkun** [comment]
It seems [compatibility test](https://github.com/pingcap/br/blob/master/.github/workflows/compatible_test.yml) failed.

@3pointer please take a look.

**Comment by tisonkun** [comment]
closed by https://github.com/pingcap/br/pull/1161

**Comment by tisonkun** [comment]
@Leavrth sorry, I think the test still failed on master. Because [pull-request-comment-trigger](https://github.com/marketplace/actions/pull-request-comment-trigger) doesn't work properly on push event.

**Comment by Leavrth** [comment]
> @Leavrth sorry, I think the test still failed on master. Because [pull-request-comment-trigger](https://github.com/marketplace/actions/pull-request-comment-trigger) doesn't work properly on push event.

pr #1170 try to fix it.

**Comment by tisonkun** [comment]
@Leavrth Thanks! If you are sure the pull request would fix, you can edit its description adding `fix #1167`

**Comment by tisonkun** [comment]
@Leavrth can we close this issue? I think it is resolved.
