### ISSUE TITLE
Import speed too slow while lightning import 30TB data to bigcluster

### ISSUE THREAD

**Issue by XuJianxu** [pingcap/br#1203]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
Use 12 lightning(2.5TB each) to import 30TB data to tidb bigcluster.
8 lightning  import to table1
2 lightning import to table2
1 lightning import to table3
1 lightning import to table4

2. What did you expect to see?
Each lightning import speed near expect number.

3. What did you see instead?
Only 400GB/18H(22GB/H) for table 4 
Only 180GB/18H(10GB/H) for table 3

4. What version of BR and TiDB/TiKV/PD are you using?
tidb-lightning -V5.1.0-20210608
tidb-server -V5.1.0-20210608
tikv-server -V5.1.0-20210608
pd-server -V5.1.0-20210608

5. Operation logs

6. Configuration of the cluster and the task

7. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus if possible

**Comment by XuJianxu** [comment]
Tidb environment：
172.16.6.6  tiup cluster display BC
lightning client:
172.16.6.9-14,28.29 for table1
172.16.6.31-32 for table2
172.16.6.33 for table 3
172.16.6.34 for table4

**Comment by glorv** [comment]
closed by https://github.com/pingcap/br/pull/1215
