### ISSUE TITLE
The prompt message is inaccurate while pre-check failed.

### ISSUE THREAD

**Issue by XuJianxu** [pingcap/br#1219]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
Use lightning to import data to TiDB. Pre-check is available.

2. What did you expect to see?
If pre-check failed, error log need to like below:
Error: lightning pre check failed.please fix the check item and make check passed or set **--check-requirements=false** to **skip** this check

3. What did you see instead?
Error: lightning pre check failed.please fix the check item and make check passed or set **--check-requirement=false** to **avoid** this check

4. What version of BR and TiDB/TiKV/PD are you using?

tidb-lightning -V5.1.0-20210611
tidb-server -V5.1.0-20210611
tikv-server -V5.1.0-20210611
pd-server -V5.1.0-20210611

5. Operation logs
   - Please upload `br.log` for BR if possible
   - Please upload `tidb-lightning.log` for TiDB-Lightning if possible
   - Please upload `tikv-importer.log` from TiKV-Importer if possible
   - Other interesting logs

6. Configuration of the cluster and the task
   - `tidb-lightning.toml` for TiDB-Lightning if possible
   - `tikv-importer.toml` for TiKV-Importer if possible
   - `topology.yml` if deployed by TiUP

7. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus if possible

**Comment by 3pointer** [comment]
#1280 close this issue.
