### ISSUE TITLE
Lightning - The empty table displayed while use --check-requirements=false to skip the lightning pre-check  

### ISSUE THREAD

**Issue by XuJianxu** [pingcap/br#1221]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
Use --check-requirements=false to skip the pre-check while import data to TiDB via lighting. 

2. What did you expect to see?
Log printed correctly

3. What did you see instead?
The empty table displayed, looks like below:
+---+------------+------+--------+
| # | CHECK ITEM | TYPE | PASSED |
+---+------------+------+--------+
+---+------------+------+--------+

4. What version of BR and TiDB/TiKV/PD are you using?

tidb-lightning -V5.1.0-20210611
tidb-server -V5.1.0-20210611
tikv-server -V5.1.0-20210611
pd-server -V5.1.0-20210611

5. Operation logs
   - Please upload `br.log` for BR if possible
   - Please upload `tidb-lightning.log` for TiDB-Lightning if possible
   - Please upload `tikv-importer.log` from TiKV-Importer if possible
   - Other interesting logs

6. Configuration of the cluster and the task
   - `tidb-lightning.toml` for TiDB-Lightning if possible
   - `tikv-importer.toml` for TiKV-Importer if possible
   - `topology.yml` if deployed by TiUP

7. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus if possible

**Comment by 3pointer** [comment]
close due to #1220 fix it
