### ISSUE TITLE
Lightning log need to imporve 

### ISSUE THREAD

**Issue by XuJianxu** [pingcap/br#1232]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
Use lightning to import the data, and do not skip the pre-check
tidb-lightning -config=lightning.toml 

2. What did you expect to see?
The error log describe accurately

3. What did you see instead?
 Below log displayed:
 _Cluster has read flow more than expection_ 

4. What version of BR and TiDB/TiKV/PD are you using?

tidb-lightning -V5.1.0-20210615
tidb-server -V5.1.0-20210615
tikv-server -V5.1.0-20210615
pd-server -V5.1.0-20210615

5. Operation logs
   - Please upload `br.log` for BR if possible
   - Please upload `tidb-lightning.log` for TiDB-Lightning if possible
   - Please upload `tikv-importer.log` from TiKV-Importer if possible
   - Other interesting logs

6. Configuration of the cluster and the task
   - `tidb-lightning.toml` for TiDB-Lightning if possible
   - `tikv-importer.toml` for TiKV-Importer if possible
   - `topology.yml` if deployed by TiUP

7. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus if possible

**Comment by sleepymole** [comment]
Fixed by https://github.com/pingcap/br/pull/1247.
