### ISSUE TITLE
Lightning import always report "the number of cluster read_flows more than expected"

### ISSUE THREAD

**Issue by XuJianxu** [pingcap/br#1233]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
Use lightning to import the data, and do not skip the pre-check
tidb-lightning -config=lightning.toml

2. What did you expect to see?
If no heavy workload in tidb, all pre-check will pass.

3. What did you see instead?
Performance pre-check fail even the tidb cluster was new deployed.
![image](https://user-images.githubusercontent.com/23207893/122215126-74f15780-cedd-11eb-87ec-fc5687faed0e.png)

4. What version of BR and TiDB/TiKV/PD are you using?

tidb-lightning -V5.1.0-20210615
tidb-server -V5.1.0-20210615
tikv-server -V5.1.0-20210615
pd-server -V5.1.0-20210615

5. Operation logs
   - Please upload `br.log` for BR if possible
   - Please upload `tidb-lightning.log` for TiDB-Lightning if possible
   - Please upload `tikv-importer.log` from TiKV-Importer if possible
   - Other interesting logs

6. Configuration of the cluster and the task
   - `tidb-lightning.toml` for TiDB-Lightning if possible
   - `tikv-importer.toml` for TiKV-Importer if possible
   - `topology.yml` if deployed by TiUP

7. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus if possible

**Comment by glorv** [comment]
closed by #1247

**Comment by cyliu0** [comment]
![Lark20210714-173200](https://user-images.githubusercontent.com/35356271/125599598-5343b73e-6831-46a5-8bc4-1d88811ac1fb.png)
still got this precheck failed. @3pointer

**Comment by cyliu0** [comment]
The above is a similar one, write flow, not exactly the same.

**Comment by 3pointer** [comment]
@cyliu0 does the cluster has other workload when import starts.

**Comment by cyliu0** [comment]
> @cyliu0 does the cluster has other workload when import starts.

No workload. Before the import, I dropped the same data which is not very large, only 10 warehouses tpcc data. This is the only operation that might lead to this.

**Comment by 3pointer** [comment]
Ok, then I think the writeflow and readflow is not a proper check item. I think we may find another way to detect workload.

**Comment by fengou1** [comment]
Still study the lightning code, need more time to understand read flow logic.

**Comment by Leavrth** [comment]
Each time HeartBeat will report the difference between `current-total-written-bytes` and `last-report-written-bytes`, so I think it's correct to use these variables to check the current cluster load.

https://github.com/tikv/tikv/blob/8defb3b243ce74a5791453c6c9061454a101be10/components/raftstore/src/store/worker/pd.rs#L1250-L1253

Unfortunately, the time interval for PD to request heartbeat is `1 min`, so there might be delayed information we obeserved.

https://github.com/tikv/pd/blob/fab46b3a56352a318d15479a1ede9169eee41e0a/server/schedule/hbstream/heartbeat_streams.go#L34

Is the time interval between `pre-check` and `drop` opration within a minute?

**Comment by fengou1** [comment]
resolved by PR: https://github.com/pingcap/br/pull/1373
