### ISSUE TITLE
lightning import progress/speed not accurate

### ISSUE THREAD

**Issue by fubinzh** [pingcap/br#1278]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
  1. Use 12 lighting nodes to import about 30TB data to TiDB, details as below
  12*2.5TB lightning, 8 *lightning->table 8, 2*lightning ->table 31, 1*lightning->table 33, 1*lightning->table 34
  2. Check the tidb-lightning log and grafana logs for lightning progress.

2. What did you expect to see?
 Progress/speed in tidb-lightning log should be accurate.

3. What did you see instead?
After about 3 hours, check the progress.
From grafana, tiks store size increase 35TB from 6TB to 40 TB. (tikv max-replicas is configured to 3)
![image](https://user-images.githubusercontent.com/7403864/123232390-b0a6a580-d50b-11eb-9045-0ac3210c1262.png)

- Store size increase by 35TB means over 1/3 of importing was finished, but tidb-lightning log is much less than that.
- Average speed  is about 1049MB/S,  (40  - 6) * 1000 * 1000 / 3 (replicas) / 10800 ( 3 hours) 
From tidb-lightning log, we can see the average speed is far slower than that,  refer to below log for details.

[lightning.speed.log](https://github.com/pingcap/br/files/6707704/lightning.speed.log)

== tikv replicas is set to 3.
root@IDC-172-16-6-6 ~]# tiup ctl:v5.1.0 pd config show all | grep replicas
    "max-replicas": 3,

4. What version of BR and TiDB/TiKV/PD are you using?

tidb: 5.1.0
lightning: 5.1.0

5. Operation logs
   - Please upload `br.log` for BR if possible
   - Please upload `tidb-lightning.log` for TiDB-Lightning if possible
   - Please upload `tikv-importer.log` from TiKV-Importer if possible
   - Other interesting logs

6. Configuration of the cluster and the task
   - `tidb-lightning.toml` for TiDB-Lightning if possible
   - `tikv-importer.toml` for TiKV-Importer if possible
   - `topology.yml` if deployed by TiUP

7. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus if possible

**Comment by sleepymole** [comment]
Replaced by https://github.com/pingcap/tidb/issues/33283.
