### ISSUE TITLE
lightning: flag parse error "tikv-importer.backend must not be empty!"

### ISSUE THREAD

**Issue by cyliu0** [pingcap/br#1321]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
Import data w/ option `-tidb-password  -backend local`

2. What did you expect to see?
Error should be empty tidb password 

3. What did you see instead?
```
/ # /tidb-lightning -d "s3://tpcc/10-warehouses-csv?access-key=minioadmin&secret-access-key=minioadmin&endpoint=http%3a%2f%2fminio.ping
cap.net%3a9000&force-path-style=true" -pd-urls "http://target-pd.testbed-2h8mp.svc:2379" -tidb-host target-tidb.testbed-2h8mp.svc:4000
-tidb-port 4000 -tidb-user root -tidb-password  -backend local -sorted-kv-dir /tmp/sorted-kv-dir
Verbose debug logs will be written to /tmp/lightning.log.2021-07-07T09.39.27Z

tidb lightning encountered error:  tikv-importer.backend must not be empty!
/ # cat /tmp/lightning.log.2021-07-07T09.39.27Z
[2021/07/07 09:39:27.593 +00:00] [ERROR] [main.go:90] ["tidb lightning encountered error stack info"] [error="tikv-importer.backend must not be empty!"] [errorVerbose="tikv-importer.backend must not be empty!\ngithub.com/pingcap/br/pkg/lightning/config.(*Config).Adjust\n\tgithub.com/pingcap/br/pkg/lightning/config/config.go:576\ngithub.com/pingcap/br/pkg/lightning.(*Lightning).RunOnce\n\tgithub.com/pingcap/br/pkg/lightning/lightning.go:182\nmain.main.func2\n\tcommand-line-arguments/main.go:86\nmain.main\n\tcommand-line-arguments/main.go:87\nruntime.main\n\truntime/proc.go:225\nruntime.goexit\n\truntime/asm_amd64.s:1371"]
[2021/07/07 09:39:27.594 +00:00] [ERROR] [main.go:91] ["tidb lightning encountered error"] [error="tikv-importer.backend must not be empty!"]
⁣/ # /tidb-lightning -V
Release Version: v5.0.0-master
Git Commit Hash: df27ac2045fa5f3942bae79a0aa20b58689145bf
Git Branch: master
Go Version: go1.16.4
UTC Build Time: 2021-07-06 04:28:09
Race Enabled: false
```

4. What version of BR and TiDB/TiKV/PD are you using?

5. Operation logs
   - Please upload `br.log` for BR if possible
   - Please upload `tidb-lightning.log` for TiDB-Lightning if possible
   - Please upload `tikv-importer.log` from TiKV-Importer if possible
   - Other interesting logs

6. Configuration of the cluster and the task
   - `tidb-lightning.toml` for TiDB-Lightning if possible
   - `tikv-importer.toml` for TiKV-Importer if possible
   - `topology.yml` if deployed by TiUP

7. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus if possible

**Comment by gozssky** [comment]
`-backend` was mistakenly treated as the values of  `-tidb-password`, so the `backend` flag was not actually set. This is because go's flag package always take the next argument as the value for previous flag but not check whether this is a flag, refer: [go/flag](https://github.com/golang/go/blob/go1.16.5/src/flag/flag.go#L967).

**Comment by cyliu0** [comment]
So could we close this one?

**Comment by gozssky** [comment]
> So could we close this one?

I think it can be changed to a feature request.

**Comment by kennytm** [comment]
i'm not sure what can we do aside from replacing the entire go/flag logic 😕

**Comment by sleepymole** [comment]
As discussed before, this was not caused by a bug. So now I am going to close this issue.
