### ISSUE TITLE
v5.1.0 - lightning - clustered-index table import speed has a downward trend

### ISSUE THREAD

**Issue by glkappe** [pingcap/br#1324]
tidb：v5.0.3
lightning: v5.1.0 
This is a clustered index table, the primary key contains multiple columns

![image](https://user-images.githubusercontent.com/21033020/124776248-de5f0600-df71-11eb-9c06-2179fb4d03b8.png)

Please help explain the reason for this situation and the improvement plan. This is also a good opportunity to help us learn the principle of lightning.

**Comment by kennytm** [comment]
are the primary keys sorted in the files, or just in arbitrary order?

**Comment by glkappe** [comment]
from v4.0.13 dumpling,so i think in arbitrary order
@lichunzhu please take a look

**Comment by IANTHEREAL** [comment]
@glkappe what the result? does user finish migration using lightning?

**Comment by glkappe** [comment]
> @glkappe what the result? does user finish migration using lightning?

yes，import success.

**Comment by sleepymole** [comment]
We have improved the behavior in v5.3. If the clustered pk is not sorted, lightning will sort them fully in the local disk.
