### ISSUE TITLE
v5.1.0 - lightning - split region retry more than three times

### ISSUE THREAD

**Issue by glkappe** [pingcap/br#1327]
Placeholder, wait for me to provide logs

**Comment by glkappe** [comment]
aws 环境
i3 16xlarge lightning，默认配置，45 tikv i3 4xlarge 
单单是记录这个问题吧，log 涉及敏感信息，没拿到。

辛苦看下这个 issue 是有保留的价值，没有可以通知我 close

**Comment by glorv** [comment]
From the issue tracking document, the root cause of lightning exit is `sighup` signal. I strongly think this is releated to the aws ec2 design when the ssh session exit.  So This issue is irrelevent and should be close. Feel free to repoen it or create a new one if this kind of issue is met again.
