### ISSUE TITLE
Rename `status/help-wanted` to `help wanted`

### ISSUE THREAD

**Issue by tisonkun** [pingcap/br#1337]
See also https://github.com/pingcap/tidb/issues/25869

GitHub supports shows issues with "help wanted" label on the repository (see below) and it is one of [default labels](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels#about-default-labels) for all repositories. We'd better name it as normal as most developers assume it to be.

![image](https://user-images.githubusercontent.com/18818196/124109379-a3ecf900-da99-11eb-94dc-d09a4827ea9e.png)

... when you click the link, you will be redirected to https://github.com/pingcap/docs-cn/issues?q=label%3A%22help+wanted%22+is%3Aissue+is%3Aopen

cc @lonng @kennytm

**Comment by kennytm** [comment]
BR does not have a `status/help-wanted` label. It is using `help wanted` now.

https://github.com/pingcap/br/labels?q=help
