### ISSUE TITLE
`tiup` and `lightning` not working well together.

### ISSUE THREAD

**Issue by dveeden** [pingcap/br#1350]
1. What did you do?

Use `tiup tidb-lightning -backend=tidb -tidb-host=...`

2. What did you expect to see?

Use the specified host

3. What did you see instead?

Usage info

4. What version of BR and TiDB/TiKV/PD are you using?

```
Release Version: v5.1.0
Git Commit Hash: f2fcbfa5a9783e33ff44b696920d8bbe6a19eaa6
Git Branch: heads/refs/tags/v5.1.0
Go Version: go1.16.4
UTC Build Time: 2021-06-24 07:09:26
Race Enabled: false
```

`tiup -- tidb-lightning -backend=tidb -tidb-host=...` does work.

This might be causing issue if people follow https://docs.pingcap.com/tidbcloud/public-preview/migrate-data-into-tidb#step-2-import-data-to-your-tidb-cluster and use `tiup` instead of manually downloading and updating binaries.

**Comment by kennytm** [comment]
@dveeden can you file the issue in https://github.com/pingcap/tiup instead? we can't control how their proxy exe is implemented in this repo.

**Comment by dveeden** [comment]
Moved to pingcap/tiup
