### ISSUE TITLE
Lightning: support downgrading to row-by-row insert when batch insert meets an error

### ISSUE THREAD

**Issue by JmPotato** [pingcap/br#1366]
### Describe your feature request related problem:

Part of #1365. Usually, Lightning will insert multiple rows at once, however, this will make the error recording and skipping not that easy if it's in a batch mode. We need to support downgrading to row-by-row insert when batch insert meets an error.

### Describe the feature you'd like:

Normally, Lightning will import multiple rows like this:

```sql
start transaction;
insert into t1 values (111), (222), (333), (444);
commit;
```

If we want to record and skip any row error that occurs during this insert while not interrupt other normal data rows, we need to make the insert look like this:

```sql
start transaction;
insert into t1 values (111);
insert into t1 values (222);
insert into t1 values (333);
insert into t1 values (444);
commit;
```

Though this may lead to performance degradation, we will only downgrade to row-by-row insert when batch insert meets an error.

### Implementation

https://github.com/pingcap/br/blob/a6f471e8e1d1db0fe4c07f96ff25a42eadd4558f/pkg/lightning/backend/tidb/tidb.go#L366-L384

`(*tidbBackend).WriteRows` will split data into different rows and check if the error is retryable. Retryable errors are often the result of, e.g, network problems, in which case retrying is feasible. However, errors that we need to record and skip are often caused by some fundamental errors, such as the mismatched column type, for which we only need to process further by implementing new code here.

* For the recording, we need to know the position and content of the data from the files for import.
* For the skipping, we need to only skip the row with the error and make sure the others being insert successfully.

Furthermore, metrics and tracking information are needed, such as error counts.

**Comment by JmPotato** [comment]
@kennytm PTAL, thx!

**Comment by kennytm** [comment]
i mean we should insert the downgrading between line 380 and 381. rest LGTM.
