### ISSUE TITLE
Lightning - no error hint when setting wrong in data-source-dir 

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/br#1376]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

- lightning config file has wrong data-source-dir setting, the directory does not exist, or no .csv .sql file in the directory.
- run lightning load: lightning --config lightning.toml

2. What did you expect to see?

- There is error log to remind user that the specified data-source-dir does not exist, or the directory has not any sql data to load.

3. What did you see instead?

- No any error hint, it's not friendly for users to debug this kind of usage error.

4. What version of BR and TiDB/TiKV/PD are you using?
 All lightning version

5. Operation logs
   - Please upload `br.log` for BR if possible
   - Please upload `tidb-lightning.log` for TiDB-Lightning if possible
   - Please upload `tikv-importer.log` from TiKV-Importer if possible
   - Other interesting logs

6. Configuration of the cluster and the task
   - `tidb-lightning.toml` for TiDB-Lightning if possible
   - `tikv-importer.toml` for TiKV-Importer if possible
   - `topology.yml` if deployed by TiUP

7. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus if possible

**Comment by sleepymole** [comment]
Fixed by https://github.com/pingcap/tidb/pull/30674.
