### ISSUE TITLE
allow use lightning tidb backend to load data to mysql #409

### ISSUE THREAD

**Issue by glkappe** [pingcap/br#1399]
https://github.com/pingcap/tidb-lightning/issues/409
@lichunzhu 
Is your feature request related to a problem? Please describe:

Describe the feature you'd like:

Allow use lightning(tidb backend) to load data to mysql compatible database. So we can completely use lightning to replace myloader.

**Comment by glorv** [comment]
already supported after https://github.com/pingcap/tidb/pull/27988
