### ISSUE TITLE
No Command line parameter for on-duplicate Lightening attribute

### ISSUE THREAD

**Issue by ankajain** [pingcap/br#1455]
## Question

I searched it everywhere, but there is no lightening command option which supports on-duplicate attribute.
In my use case for 1 migration I want it to be ignore (to avoid overhead as there is no updates on existing record )in 1 use case and replace in another use case.
Creating multiple file doesn't make any sense over command line option.
So please help if we have any attribute which we can use in the command line for this.

tidb-lightning -L info -log-file Ligtening.log -status-addr :0 -backend tidb -tidb-host 127.0.0.1 -tidb-port 4000 -tidb-user root -tidb-password root -tidb-status 10080 -pd-urls 127.0.0.1:2379 -enable-checkpoint=false -d . --config lightening.toml 

Rather than using config please help me with the attribute for on-duplicate configuration.

**Comment by glorv** [comment]
@ankajain  the `on-duplicate` attribute can only be set within the config file like following:
part of tidb-lightning.toml:
```
[tikv-importer]
# Action to do when trying to insert a duplicated entry in the "tidb" backend.
#  - replace: use new entry to replace the existing entry
#  - ignore: keep the existing entry, and ignore the new entry
#  - error: report error and quit the program
on-duplicate = "replace"
```
Please refer to https://docs.pingcap.com/tidb/dev/tidb-lightning-configuration/#tidb-lightning-task for more details.

**Comment by ankajain** [comment]
@glorv 
So are we suggesting to have a separate config file as per the use case.?

**Comment by glorv** [comment]
> @glorv So are we suggesting to have a separate config file as per the use case.?

@ankajain In your case I think this is the only way to support your requirement. Because there are tens of config fields in tidb-lighting's configs, put all of them into command line parameter may not be easy to use.

**Comment by ankajain** [comment]
@glorv Thanks for the updates.
