### ISSUE TITLE
infinite loop bug in mergeSSTs tidb-lightning tool

### ISSUE THREAD

**Issue by wenlive** [pingcap/br#1464]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
With the config dataEngineCfg.Local.Compact = true , create the engine and write keys into the pebble

2. What did you expect to see?
 skip the same lastkey and key when do compact

3. What did you see instead?
log like this 
 ["duplicated key found, skipped"] [key=xxx] 
 ["duplicated key found, skipped"] [key=xxx] 
 ["duplicated key found, skipped"] [key=xxx] 
......
output a lot of the same content to the log

in the following code 
https://github.com/pingcap/br/blob/c7f93829ef433dea4a86d0eb506a19a1339e4201/pkg/lightning/backend/local/local.go#L3167
may need move the iter before continue

4. What version of BR and TiDB/TiKV/PD are you using?
i build the tidb-lightning in branch release 5.1 of tikv-br
the same questionable code of mergeSST can be found in master

5. Operation logs
   - Please upload `br.log` for BR if possible
   - Please upload `tidb-lightning.log` for TiDB-Lightning if possible
   - Please upload `tikv-importer.log` from TiKV-Importer if possible
   - Other interesting logs
 
As shown above 

6. Configuration of the cluster and the task
   - `tidb-lightning.toml` for TiDB-Lightning if possible
   - `tikv-importer.toml` for TiKV-Importer if possible
   - `topology.yml` if deployed by TiUP

7. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus if possible

**Comment by glorv** [comment]
@wenlive Thanks for your bug reporting. This is a known issue which is fixed in https://github.com/pingcap/tidb/pull/27390.  This repo is migrated into [`pingcap/tidb` ](https://github.com/pingcap/tidb) after version v5.2. You can updated to the newest version of tidb-lightning to avoid this and several other unstable bugs.

**Comment by wenlive** [comment]
Thanks
