### ISSUE TITLE
Lots of empty region after restore

### ISSUE THREAD

**Issue by overvenus** [pingcap/br#163]
Region size is not updated during BR restore, this is because we forget to set `Length` of SSTMeta. https://github.com/pingcap/br/blob/008ec45182220d6d7cc7e8b13f940bfea1e24fd6/pkg/restore/util.go#L140-L149

The `Length` means the length of the SST file, so TiKV should record it during backup as requested in #95 .

**Comment by kennytm** [comment]
This is a bug in BR only right? The `File`s in the `BackupResponse` already contained the size.

https://github.com/pingcap/kvproto/blob/dba161a41fd2edfe1349a7c7322276640642633d/proto/backup.proto#L63

**Comment by overvenus** [comment]
TiKV has not filled it yet, so we need to touch TiKV too.

**Comment by kennytm** [comment]
Ah ok.
