### ISSUE TITLE
Support multiple databases / tables

### ISSUE THREAD

**Issue by kennytm** [pingcap/br#178]
### Describe your feature request related problem:

Support backing up multiple tables in a single command without needing the --backupts trick.

### Describe the feature you'd like:

A simplified version of #173. We support the following commands to backup/restore multiple databases or tables.

```sh
./br backup database --db firstdb --db seconddb 
#                                 ^~~~~~~~~~~~~
./br backup table --???? 'firstdb.firsttable' --???? '`second.db`.`2,tbl`'
```

Because the table name can contain a `.`, we need to support quoting by `` ` ``.

Unresolved question:

* Should we change the behavior of `database --db 'db1,db2'`? (currently backing up a single database named `` "db1,db2" ``
* Should we change the behavior of ``database --db '`db`'``? (currently backing up a single database named `` "`db`" ``
* What should the `--????` parameter be named?
* Should we keep the `table --db db1 --table tbl1` form?
* Do we want to support `table --???? 'db1.tbl1,db2.tbl2'`?
* Do we want to support `table --db db1 --???? tbl1 --???? tbl2`?
* Do we want to support `table --db db1 --db db2 --???? tbl1 --???? tbl2`?
* Should we support ANSI quotes `table --???? '"db1,db2"."tbl1,tbl2"'`?
* Should we reject if the inputs aren't proper identifiers `table --???? '!@#$.%^&*'`?

### Describe alternatives you've considered:

Don't support this and go straight to #173.

### Teachability, Documentation, Adoption, Migration Strategy:

If we decide to name `--????` as `--table` we'll need to rewrite all documentations.

**Comment by 3pointer** [comment]
I suggest add new flag like `--dbs` and `--tables` to backup mutliple tables

**Comment by GregoryIan** [comment]
My suggestions are based on two principles

* The simpler the better, let the user choose as little as possible while keeping it as easy to use
* Be consistent with other tools, do not design separately

-[ ] Should we change the behavior of `database --db 'db1,db2'`? (currently backing up a single database named `` "db1,db2" ``
-[ ] Should we change the behavior of ``database --db '`db`'``? (currently backing up a single database named `` "`db`" ``
-[x] What should the `--????` parameter be named?   **I suggest `tables` **
-[x] Should we keep the `table --db db1 --table tbl1` form? ** it is not clear **
-[ ] Do we want to support `table --???? 'db1.tbl1,db2.tbl2'`?
-[x] Do we want to support `table --db db1 --???? tbl1 --???? tbl2`?
-[x] Do we want to support `table --db db1 --db db2 --???? tbl1 --???? tbl2`?
-[ ] Should we support ANSI quotes `table --???? '"db1,db2"."tbl1,tbl2"'`?
-[ ] Should we reject if the inputs aren't proper identifiers `table --???? '!@#$.%^&*'`?

**Comment by kennytm** [comment]
@3pointer  If we don't convert `--db 'db1,db2'` to `--db db1 --db db2`, adding a new `--dbs` seems pointless.

@GregoryIan  If we support `--db db1 --db db2 --db db3 --tables tbl1 --tables tbl2 --tables tbl3` it means we back up 9 (3×3) tables. Does that match what you mean? And what do you mean by

> * [x] Should we keep the `table --db db1 --table tbl1` form? ** it is not clear **

?

**Comment by GregoryIan** [comment]
one example: `--db db1  --tables tbl1 --tables tbl2  -db db2  --tables tbl2 --db db3 --tables tbl3` , means to backup`db1`.`tbl1`, `db1`.`tbl2`,`db2`.`tbl2`, `db3`.`tbl3`, can we achieve it？

**Comment by kennytm** [comment]
@GregoryIan No, `--abc def` arguments aren't unordered.

**Comment by kennytm** [comment]
we may want to make `--db a --db b` and `--table a --table b` an error, this currently confuses some users.
