### ISSUE TITLE
BR should filter out TiFlash nodes

### ISSUE THREAD

**Issue by kennytm** [pingcap/br#180]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

Backup from a cluster where some TiFlash nodes are running

2. What did you expect to see?

Success.

3. What did you see instead?

Backup failed with "Unimplemented" error in `SendBackup()`, on this line:

https://github.com/pingcap/br/blob/328ad699d00ff23f1938b4c3dff3f3e4ecc5226c/pkg/backup/client.go#L684

Since TiFlash cannot participate in BR anyway, we should just filter these nodes out.

4. What version of BR and TiDB/TiKV/PD are you using?

3.1.0-beta.1

**Comment by jebter** [comment]
This bug should block 3.1.0 GA, please fix it.

**Comment by kennytm** [comment]
@jebter do you know how to distinguish between a TiKV node and TiFlash node? PD's `/pd/api/v1/stores` API doesn't contain such information.

**Comment by jebter** [comment]
The information of the TiFlash node contains a label:
"labels": [
           {
             "key": "engine",
             "value": "tiflash"
           }
         ]
cc @nolouch
