### ISSUE TITLE
BR cannot restore to `alter-primary-key = true` server

### ISSUE THREAD

**Issue by kennytm** [pingcap/br#215]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

First set up a TiDB with [`alter-primary-key = true`](https://pingcap.com/docs/stable/reference/configuration/tidb-server/configuration-file/#alter-primary-key).

Create a table:

```sql
create table test.a (a int primary key, b int unique);
insert into test.a values (42, 42);
```

Run backup

```sh
bin/br backup table --db test -t a -s 'local:///tmp/brapk'
```

Drop the table

```sql
drop table test.a;
```

Restore

```sh
bin/br restore table --db test -t a -s 'local:///tmp/brapk'
```

2. What did you expect to see?

Restore success and checksum pass

3. What did you see instead?

An "ranges overlapped" error

```
[2020/03/27 13:38:22.085 +00:00] [ERROR] [restore.go:225] ["split regions failed"] [error="ranges overlapped: [74800000000000003b5f69800000000000000100 74800000000000003b5f698000000000000001fb],
```

4. What version of BR and TiDB/TiKV/PD are you using?

Cluster: 4.0
BR: master

**Comment by bb7133** [comment]
Maybe it's because the embedded TiDB doesn't handle `alter-primary-key` flag correctly.

**Comment by bb7133** [comment]
Please notice that with `alter-primary-key=true`, the table is created with `PKIsHandle=false` and the primary key is encoded the same way as unique index.
