### ISSUE TITLE
BR cannot incremental restore when met DDL with auto random DDL

### ISSUE THREAD

**Issue by 3pointer** [pingcap/br#228]
1. What did you do?
incremental restore met DDL with auto random would fail, reproduce it with follow step
   1.   Full backup
   2. `create table ta(`a` int(11) NOT NULL /*T!30100 AUTO_RANDOM(5) */, PRIMARY KEY (`a`))`
   3. Incremental backup
   4. Full restore
   5. Incremental restore will fail
```
Invalid auto random: auto_random is an experimental feature, which can only be used when allow-auto-random is enabled. This can be changed in the configuration.
```
2. What did you expect to see?
incremental restore success

3. What did you see instead?
```
Invalid auto random: auto_random is an experimental feature, which can only be used when allow-auto-random is enabled. This can be changed in the configuration.
```

4. What version of BR and TiDB/TiKV/PD are you using?
br 3.1-rc
br 4.0-rc

**Comment by kennytm** [comment]
We should just enable all experiment features which doesn't affect existing behaviors.
