### ISSUE TITLE
BR restore performance optimize

### ISSUE THREAD

**Issue by 3pointer** [pingcap/br#255]
currently, BR restore has two main steps. 
1. perform All prepare DDL(create table + alter auto_increment).
2. restore data

For now,  step.2 will wait for step.1 finished. so the time cost will be `(step.1 + step.2)`, unfortunately 
perform per DDL will cost 1~2s in TiDB, and we can't do parallel perform due to TiDB restriction. 
but we pipeline above steps to reduce cost to `max(step.1, step.2)`.

Following things to do:
- [ ] https://github.com/pingcap/br/issues/219 Add retry on batchRegionSplit.
- [ ] pipeline two steps.
- [ ] finish test report.

**Comment by YuJuncen** [comment]
the test binary of pipelining restore process is developed based on #219, but it was cherry-picked to a new branch based on `br:master`. I think it's OK to merge #266 firstly then #219, since the last one is blocked by import `failpoint` to test.

**Comment by YuJuncen** [comment]
#219 make more affects to #214, which is blocked by the test case. (B.T.W. #219 itself is blocked by its test cases too... Is this fate?)
