### ISSUE TITLE
make concurrency setting more clear

### ISSUE THREAD

**Issue by 3pointer** [pingcap/br#269]
### Describe your feature request related problem:

user may confuse about concurrency setting, because Restore concurrency default value is 128, but Backup concurrency default value is 4.

### Describe the feature you'd like:

1. give a warning when user didn't set proper value of concurrency.

### Describe alternatives you've considered:

1. update document to make it more clearly
> * remove concurrency introduction in document
> * remove rate-limit introduction in document

**Comment by kennytm** [comment]
Everything causing this issue has been fixed. Closing.
