### ISSUE TITLE
Backup fails with DefaultNotFound error

### ISSUE THREAD

**Issue by overvenus** [pingcap/br#282]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

BR backup table occurs "default not found error", it means we found a commit record in Write CF but unable to find the corresponding value in Default CF.

<details><summary>Failed table schema</summary>
<p>

```sql
CREATE TABLE `t` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `a` int(10) unsigned NOT NULL,
  `b` varchar(64) NOT NULL DEFAULT '',
  `c` tinyint(4) DEFAULT '1',
  `d` int(11) NOT NULL,
  `e` int(11) NOT NULL DEFAULT '0',
  `f` bigint(20) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `a` (`a`),
  KEY `f` (`f`)
) ENGINE=InnoDB
``` 

</p>
</details>

2. What did you expect to see?

Backup table successfully.

3. What did you see instead?

Backup fails with DefaultNotFound error.

4. What version of BR and TiDB/TiKV/PD are you using?

TiDB 3.1-GA
BR 3.1-GA

**Comment by kennytm** [comment]
is there more details about how this bug can be reproduced (or still investigating?)

**Comment by overvenus** [comment]
Still investigating.

Current progress:
1. bad txn key is in correct backup range.
<details><summary>backup range</summary>
<p>

```
/data/deploy/log/tikv-051015.log:[2020/05/10 15:08:37.997 +08:00] [ERROR] [endpoint.rs:664] ["backup region failed"] [error="Txn(Mvcc(DefaultNotFound { key: [116, 128, 0, 0, 0, 0, 0, 3, 250, 95, 114, 128, 0, 0, 0, 91, 0, 149, 32], write: Write { write_type: Put, start_ts: 415573961555839715, short_value: \"None\" } }))"] [end_key=] [start_key=] [region="id: 1629348 start_key: 7480000000000003FFFA5F72800000005AFFFFC6B00000000000FA end_key: 7480000000000003FFFA5F72800000005BFF0DAAE70000000000FA region_epoch { conf_ver: 11009 version: 812 } peers { id: 2668350 store_id: 5 } peers { id: 4230159 store_id: 4 } peers { id: 4713441 store_id: 1428950 }"]
```

From the error above, we know the bad txn key is
```
$ mok 7480000000000003FA5F72800000005B009520
"7480000000000003FA5F72800000005B009520"
└─## decode hex key
  └─"t\200\000\000\000\000\000\003\372_r\200\000\000\000[\000\225 "
    └─## table row key
      ├─table: 1018
      └─row: 1526764832
```  

And it's in the middle of region `["7480000000000003FFFA5F72800000005AFFFFC6B00000000000FA", "7480000000000003FFFA5F72800000005BFF0DAAE70000000000FA")`, a valid range for the backup task. 

</p>
</details>

2. User data is intact, as `admin check table xxx` returns OK 
<details><summary>admin check table</summary>
<p>

![image](https://user-images.githubusercontent.com/2150711/81931322-7a1a0e00-961c-11ea-9614-c24a27a5b028.png)
 
</p>
</details>
