### ISSUE TITLE
Restoring auto_random leads to "invalid ddl job type: none"

### ISSUE THREAD

**Issue by kolbe** [pingcap/br#289]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

I took a single-table backup that has auto_random enabled.

2. What did you expect to see?

3. What did you see instead?

Restoring gives a "invalid ddl job type: none" error in the backup. Full br.log attached. 

[br.log.2020-05-14T16.50.55-0700.txt](https://github.com/pingcap/br/files/4631586/br.log.2020-05-14T16.50.55-0700.txt)

4. What version of BR and TiDB/TiKV/PD are you using?

```
$ ./bin/br -V
Release Version: v4.0.0-beta.2-35-g943e502
Git Commit Hash: 943e502cc14da6bff81d15b78d2468500526a44b
Git Branch: master
Go Version: go1.14
UTC Build Time: 2020-05-13 07:47:54
Race Enabled: false

$ /Users/kolbe/.tiup/components/pd/v4.0.0-rc.1/pd-server -V
Release Version: v4.0.0-rc.1
Git Commit Hash: 31dae220db6294f2dc2ec0df330892fe76e59edc
Git Branch: HEAD
UTC Build Time:  2020-04-28 01:53:08

$ /Users/kolbe/.tiup/components/tidb/v4.0.0-rc.1/tidb-server -V
Release Version: v4.0.0-rc.1
Git Commit Hash: 7267747ae0ec624dffc3fdedb00f1ed36e10284b
Git Branch: HEAD
UTC Build Time: 2020-04-28 01:48:29
GoVersion: go1.13.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

$ /Users/kolbe/.tiup/components/tikv/v4.0.0-rc.1/tikv-server -V
TiKV
Release Version:   4.0.0-rc.1
Git Commit Hash:   e8053b3e3d361acc3def3131aa01c3aa674d2561
Git Commit Branch: HEAD
UTC Build Time:    2020-04-28 02:50:34
Rust Version:      rustc 1.42.0-nightly (0de96d37f 2019-12-19)
Enable Features:   jemalloc sse protobuf-codec
Profile:           dist_release
```

**Comment by kolbe** [comment]
[br-289-cluster-logs.zip](https://github.com/pingcap/br/files/4631599/br-289-cluster-logs.zip)

**Comment by 3pointer** [comment]
It seems TiDB 7267747ae0ec624dffc3fdedb00f1ed36e10284b doesn't support auto_random DDL. I think update TiDB version to latest after this https://github.com/pingcap/tidb/pull/16813 merged can solve this problem.

**Comment by kolbe** [comment]
OK. I think BR needs better support for a situation where something like this happens and the cluster it's restoring to doesn't support some piece of DDL being used!

**Comment by 3pointer** [comment]
is this problem still reproducible? shall we close it?
