### ISSUE TITLE
Update document about impact on cluster

### ISSUE THREAD

**Issue by 3pointer** [pingcap/br#295]
### Describe your feature request related problem:

Add backup impact on online cluster in official [document](https://pingcap.com/docs-cn/dev/br/backup-and-restore-tool/).

**Comment by 3pointer** [comment]
https://github.com/pingcap/tidb-lightning/pull/324

**Comment by kennytm** [comment]
@3pointer that doesn't seem to be the correct PR for this issue.

**Comment by 3pointer** [comment]
> @3pointer that doesn't seem to be the correct PR for this issue.

Updated
