### ISSUE TITLE
BR registers itself as TiDB

### ISSUE THREAD

**Issue by breeswish** [pingcap/br#299]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

Start BR

2. What did you expect to see?

TiDB instance list unchanged.

3. What did you see instead?

A new TiDB instance is added as below:

![image](https://user-images.githubusercontent.com/1916485/82306348-88d43c80-99f1-11ea-9ae0-16a4b3f96fca.png)

4. What version of BR and TiDB/TiKV/PD are you using?

**Comment by kennytm** [comment]
As discussed in https://app.slack.com/client/TH91JCS4W/C013HGZMBAR/thread/C013HGZMBAR-1589455570.035500, TiDB will need to expose an option to avoid registering itself on PD and avoid making itself as the DDL owner.

**Comment by breeswish** [comment]
Yes, the issue is opened so that it can be tracked.

**Comment by kennytm** [comment]
Regarding all kinds of registrations, we could avoid registering BR as a DDL Owner by [setting `run-ddl = false`](https://github.com/pingcap/tidb/blob/23759514ec8d4bae275e0591f1f45d9fd2cdba1f/config/config.toml.example#L21-L22). 

However, if the cluster has no DDL owners (e.g. there are zero TiDBs in the cluster), the DDLs executed in BR will be stuck, rather than reporting an error.

**Comment by YuJuncen** [comment]
> Regarding all kinds of registrations, we could avoid registering BR as a DDL Owner by [setting `run-ddl = false`](https://github.com/pingcap/tidb/blob/23759514ec8d4bae275e0591f1f45d9fd2cdba1f/config/config.toml.example#L21-L22).
> 
> However, if the cluster has no DDL owners (e.g. there are zero TiDBs in the cluster), the DDLs executed in BR will be stuck, rather than reporting an error.
> 
> An alternative is to tweak the campaign so that BR becomes the least favorable candidate, but I'm not sure if it is possible with the etcd interface.

According to @zimulala , if we can become the DDL owner, the speed of executing DDL
 will boost(from 1s to <100ms). So, if possible, could we temporarily make the embedded TiDB become DDL owner?

We can take good from this if we make offline restore(i.e. nobody wants to execute DDL during restoring) at brand new cluster. Separately, we can also prevent from register BR by disable `topologySyncer`.

But we must talk to TiDB folks and make some discussions to ensure the risks and the feasibility of that.

**Comment by breeswish** [comment]
I see that this issue is closed by  pingcap/tidb#17513 instead of a BR pull request. Maybe we need to re-open it?
