### ISSUE TITLE
BR log is weird

### ISSUE THREAD

**Issue by zhouqiang-cl** [pingcap/br#304]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
when running br, there is no newline

![企业微信截图_21a3a904-9b6a-455d-b2b0-4941f5520a62](https://user-images.githubusercontent.com/23521459/82777583-1f38b000-9e81-11ea-8a62-5c78af845f26.png)

2. What did you expect to see?
has new line

3. What did you see instead?
see pic

4. What version of BR and TiDB/TiKV/PD are you using?

```
Release Version: v4.0.0-rc.2
Git Commit Hash: 2d645076ea3663b687151201ae19dfdc497186bb
Git Branch: heads/refs/tags/v4.0.0-rc.2
Go Version: go1.13
UTC Build Time: 2020-05-15 10:38:13
Race Enabled: false
```

**Comment by kennytm** [comment]
This is more likely a problem of the terminal not fully understanding the ANSI sequence (or being stripped out by tmux (?)). 

Which terminal are you using?

**Comment by zhouqiang-cl** [comment]
It is default terminal😯

**Comment by kennytm** [comment]
macOS? Windows? Ubuntu?

**Comment by zhouqiang-cl** [comment]
macOS
