### ISSUE TITLE
BR check backup directory is empty before backup start

### ISSUE THREAD

**Issue by 3pointer** [pingcap/br#328]
### Describe your feature request related problem:
User may backup to same directory when last backup failed and we only check `backupmeta` before backup start.

### Describe the feature you'd like:

Check backup directory is empty before start.

**Comment by kennytm** [comment]
Empty means the directory has no content, or just does not contain `backupmeta`, `backupmeta.json` and `*.sst`?

**Comment by 3pointer** [comment]
> Empty means the directory has no content, or just does not contain `backupmeta`, `backupmeta.json` and `*.sst`?

I think  just check backupmeta and *.sst is enough.
