### ISSUE TITLE
DDL through CreateDatabase or CreateTable gets wrong query

### ISSUE THREAD

**Issue by wjhuang2016** [pingcap/br#364]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

We need to set the query for the DDL, [like this](https://github.com/pingcap/tidb/blob/7daa4a7f88194a9d4317a27acdf2143312375cd5/session/session.go#L1187)

```go
se.SetValue(sessionctx.QueryString, s.OriginText())
```

But we didn't set it, so query in DDL history is wrong.

4. What version of BR and TiDB/TiKV/PD are you using?

**Comment by kennytm** [comment]
@wjhuang2016 how will the query string be used, aside from presenting human-readable information? the "DDL" cannot be represented as an SQL string (e.g. you can't expose the alter-pk-ability in the CREATE TABLE statement), so using `ConstructResultOfShowCreateTable` would be misleading.

**Comment by wjhuang2016** [comment]
> @wjhuang2016 how will the query string be used, aside from presenting human-readable information? the "DDL" cannot be represented as an SQL string (e.g. you can't expose the alter-pk-ability in the CREATE TABLE statement), so using `ConstructResultOfShowCreateTable` would be misleading.

Would you mean `ConstructResultOfShowCreateTable` do more than creating a table?

**Comment by kennytm** [comment]
DM should not replicate the BACKUP/RESTORE statements

**Comment by wjhuang2016** [comment]
> DM should not replicate the BACKUP/RESTORE statements

I mean, the create table statement or create schema statement here.

**Comment by kennytm** [comment]
we should make DM filter them out as well

**Comment by wjhuang2016** [comment]
> we should make DM filter them out as well

Sorry, it's not the DM goes wrong. It's the drainer. If we use BR from A to B, then use drainer from B to C.  Since the DDL query is wrong, drainer will send to the wrong SQL to C.

**Comment by wjhuang2016** [comment]
@kennytm Any comment?

**Comment by kennytm** [comment]
Current consensus:

1. Binlog-drainer and CDC should be interrupted when receiving a BR restore action, because there is no way to tell the downstream where to download the SST files. 
2. In order for Binlog/CDC to properly filter out the DDLs, they must still be in correct syntax.

**Comment by wjhuang2016** [comment]
> Current consensus:
> 
> 1. Binlog-drainer and CDC should be interrupted when receiving a BR restore action, because there is no way to tell the downstream where to download the SST files.
> 2. In order for Binlog/CDC to properly filter out the DDLs, they must still be in correct syntax.

According to the 2,  we need to set the correct statement for these DDLs. Please fix it before the next release.

**Comment by kennytm** [comment]
Which? 4.0.3?

**Comment by wjhuang2016** [comment]
> Which? 4.0.3?

Yeah.

**Comment by 3pointer** [comment]
> > Current consensus:
> > 
> > 1. Binlog-drainer and CDC should be interrupted when receiving a BR restore action, because there is no way to tell the downstream where to download the SST files.
> > 2. In order for Binlog/CDC to properly filter out the DDLs, they must still be in correct syntax.
> 
> According to the 2, we need to set the correct statement for these DDLs. Please fix it before the next release.

set the correct statement for these DDLs is not enough. because this only postpone the interruption to next related DML. maybe given a special DDL or DDL job to let downstream(Binlog/CDC) know they should skip these DDL and add these new created schema to block list automatically is better.

I want to know what do you think @kennytm

**Comment by YuJuncen** [comment]
We can use `executor.ConstructResultOfCreateTable` to make the right DDL, but the problem is that `tidb/executor` requires `br`...

As what @3pointer said, since the downstream always cannot handle these DDLs rightly, why doesn't we not to provide right DDL but just provide some hints? Like simply `/* brie({tables: ["db1.t1", "db1.t2"], from: "BR"}) */`?

**Comment by kennytm** [comment]
@YuJuncen there is no cyclic dependency if you exclusively do it inside the glue package.
