### ISSUE TITLE
Do not create irrelevant tables when use incremental restore

### ISSUE THREAD

**Issue by 3pointer** [pingcap/br#365]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
  a.  we have a cluster with 100+ table and full backup.
  b.  create a new table then do incremental backup.
  c.  restore full backup to new cluster
  d.  restore incremental backup,

2. What did you expect to see?
   step d. will do lots of create table ddl according to log and cost lots of time. I believe that is unnecessary. 

3. What did you see instead?
   step d. only create newly table.

4. What version of BR and TiDB/TiKV/PD are you using?
all

**Comment by YuJuncen** [comment]
When we creating table, we use `IF NOT EXIST` condition(Seems when table exists, TiDB didn't send it to DDL job  queue but return immediately after fetching schema and found out the table exists). What we need to do all is just restore some 'metadata', but sometimes this might be necessary?
