### ISSUE TITLE
Adjust backup concurrency before BR started.

### ISSUE THREAD

**Issue by 3pointer** [pingcap/br#394]
### Describe your feature request related problem:

Current default config (e.g. concurrency) for BR is not enough. for some highly performance cluster default backup concurrency 4 and restore concurrency 128 is not fit. 

### Describe the feature you'd like:

Maybe we should add some check before BR progress started, to tell user adjust these config manually or do it automatically.

**Comment by kennytm** [comment]
See tikv/tikv#8076 for backup concurrency.

**Comment by kennytm** [comment]
Regarding backup concurrency, I think we should modify the meaning like this:

1. change the TiKV backup thread-pool size (tikv/tikv#8076) from a value specified by the gRPC request to a TiKV config defaulting to 1/2 of number of vCPU.
2. change this to run in parallel, and make backup concurrency control the pool size.

    https://github.com/pingcap/br/blob/aa4b7d51a96d51c2236d92f0d16a1c09eda2062c/pkg/backup/client.go#L394-L404

**Comment by kennytm** [comment]
Note that the cluster causing this issue contains a table with 6 secondary indices and 125 partitions, thus generating 875 ranges for this table alone.
