### ISSUE TITLE
Support different compression algorithm in BR

### ISSUE THREAD

**Issue by overvenus** [pingcap/br#395]
### Describe your feature request related problem:

By default, BR uses lz4 to compress backup files (sst). lz4 is fast but not very effective in its compression ratio.

According to [RasterLite2 reference Benchmarks](https://www.gaia-gis.it/fossil/librasterlite2/wiki?name=benchmarks+%282019+update%29), we could try a different compression algorithm to improve overall backup speed.

### Describe the feature you'd like:

Support different compression algorithm in BR

### Describe alternatives you've considered:

N/A

### Teachability, Documentation, Adoption, Migration Strategy:

N/A

**Comment by kennytm** [comment]
The range of choices depends on what kinds of compression RocksDB supports. Currently these algorithms are recognized:

* (no)
* snappy
* zlib
* bzip2
* lz4
* lz4hc
* zstd
* zstd-not-final

Note that LZMA is not in the list.

**Comment by kennytm** [comment]
Fixed in #404.
