### ISSUE TITLE
br only support s3 remote storage?

### ISSUE THREAD

**Issue by lddlww** [pingcap/br#397]
does br support custom remote storage?

**Comment by kennytm** [comment]
BR currently only supports S3- and GCS-compatible protocols. You could also mount a networked file system on each TiKV & BR node and use the `local://` URL.

There is currently plan to support HTTP protocol (#308). 

What kind of custom remote storage are you interested in?

**Comment by lddlww** [comment]
oh thanks，```http protocol``` is enough ，cool

**Comment by kennytm** [comment]
(Closing as duplicate of #308)
