### ISSUE TITLE
Some error logs are confusing

### ISSUE THREAD

**Issue by amyangfei** [pingcap/br#403]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

https://github.com/pingcap/br/blob/8ffad37d9e917a71c59c0501f2bdbc5b9bdd853e/pkg/backup/push.go#L96-L103

Is the error `backup.Error_KvError` and `backup.Error_RegionError` retryable? If so, error log may be confused.

2. What did you expect to see?

3. What did you see instead?

4. What version of BR and TiDB/TiKV/PD are you using?

**Comment by 3pointer** [comment]
Yes, these errors are retryable. I think we can change log level to warn.
