### ISSUE TITLE
restoring data(one database) from s3 Compatible backend  failed

### ISSUE THREAD

**Issue by 2983777417** [pingcap/br#415]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
1.br backup data to s3 compatible backend successful.
./br backup db --pd "192.168.15.101:2379" --db test --storage "s3://tidb/br-20200708" --send-credentials-to-tikv true --s3.endpoint "http://sre.hcp.lfs.XXXX.com" --log-file backup_db0713_6.log --ratelimit 50 --concurrency 16 
2.br restore data from s3 compatible backend failed.
./br restore db --pd "192.168.15.214:2379" --db test --storage "s3://tidb/br-20200708" --send-credentials-to-tikv true --s3.endpoint "http://sre.hcp.lfs.XXXX.com" --log-file restore_db0713_4.log --ratelimit 8 --concurrency 2

2. What did you expect to see?
all the tables in the restoring database get the correct data.

3. What did you see instead?
tidb database condition:
All the tables structure have been generated ,but data is empty or is wrong.

br.log:
Database restore <-------------------------------------------------------------------------------------------------------------------------> 100.00%
Error: Cannot read s3://tidbbr-20200708/5_100063479_4387_c715fdf2a90372568f2b49de560a12d8755b06ede9be69f8ac0117fa04c2a687_write.sst into /data/tiup_v4_s3/tidb-data/tikv-20160/import/.temp/2b2dd626-91a7-4b0c-80db-bd172632e65e_1246_5_308_write.sst: failed to get object Error during dispatch: error trying to connect: dns error: failed to lookup address information: Name or service not known: download sst failed; 

sometime br get panic ,
```
panic: send on closed channel

goroutine 343 [running]:
github.com/pingcap/br/pkg/gluetikv.progress.Inc(0xc000d10a80)
        /home/tidb/git-workspace/br/pkg/gluetikv/glue.go:65 +0x35
github.com/pingcap/br/pkg/restore.SplitRanges.func2(0xc000a39380, 0xd, 0x10)
        /home/tidb/git-workspace/br/pkg/restore/util.go:427 +0x42
github.com/pingcap/br/pkg/restore.(*RegionSplitter).Split(0xc000b0b958, 0x34130a0, 0xc00074c580, 0xc000fdb180, 0x1, 0x1, 0xc000f00210, 0xc000b0b968, 0xc000b0b9e8, 0x2753f23)
        /home/tidb/git-workspace/br/pkg/restore/split.go:139 +0x7c7
github.com/pingcap/br/pkg/restore.SplitRanges(0x34130a0, 0xc00074c580, 0xc0009c34a0, 0xc000fdb180, 0x1, 0x1, 0xc000f00210, 0x33e9260, 0xc000d10a80, 0x0, ...)
        /home/tidb/git-workspace/br/pkg/restore/util.go:425 +0x1f0
github.com/pingcap/br/pkg/restore.(*tikvSender).RestoreBatch(0xc0004e24a0, 0x34130a0, 0xc00074c580, 0xc000fdb180, 0x1, 0x1, 0xc000f00210, 0x0, 0x0)
        /home/tidb/git-workspace/br/pkg/restore/pipeline_items.go:171 +0xa6
github.com/pingcap/br/pkg/restore.(*Batcher).Send(0xc000263b80, 0x34130a0, 0xc00074c580, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/tidb/git-workspace/br/pkg/restore/batcher.go:306 +0x3cf
github.com/pingcap/br/pkg/restore.(*Batcher).sendWorker.func1(0x0)
        /home/tidb/git-workspace/br/pkg/restore/batcher.go:132 +0x8d
github.com/pingcap/br/pkg/restore.(*Batcher).sendWorker(0xc000263b80, 0x34130a0, 0xc00074c580, 0xc0005ae150)
        /home/tidb/git-workspace/br/pkg/restore/batcher.go:150 +0xae
created by github.com/pingcap/br/pkg/restore.NewBatcher
        /home/tidb/git-workspace/br/pkg/restore/batcher.go:88 +0x1db
```

4. What version of BR and TiDB/TiKV/PD are you using?

./br -V
Release Version: v4.0.0-beta.2-78-gde452e1-dirty
Git Commit Hash: de452e1af5aff6f959d22f4c6695f742653cb466
Git Branch: heads/v4.0.2
Go Version: go1.13.5
UTC Build Time: 2020-07-13 09:30:00
Race Enabled: false

./tikv-server -V
TiKV
Release Version:   4.0.1
Edition:           Community
Git Commit Hash:   78d7a854026962669ceb2ee0ac343a5e88faa310
Git Commit Branch: heads/refs/tags/v4.0.1
UTC Build Time:    2020-06-12 09:13:05
Rust Version:      rustc 1.42.0-nightly (0de96d37f 2019-12-19)
Enable Features:   jemalloc portable sse protobuf-codec
Profile:           dist_release

./pd-server -V
Release Version: v4.0.1
Edition: Community
Git Commit Hash: 30f0b014b7ff3cd1b5f041bf7ce73448dc0d0fe8
Git Branch: heads/refs/tags/v4.0.1
UTC Build Time:  2020-06-12 05:38:34

./tidb-server -V
Release Version: v4.0.1
Edition: Community
Git Commit Hash: 689a6b6439ae7835947fcaccf329a3fc303986cb
Git Branch: heads/v4.0.1
UTC Build Time: 2020-06-15 03:54:18
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

**Comment by 2983777417** [comment]
I'm trying to find why the br reading  s3 'bucket/prefix' is 'tidbbr-20200708' not 'tidb/br-20200708' ,but i failed.

**Comment by kennytm** [comment]
> I'm trying to find why the br reading s3 'bucket/prefix' is 'tidbbr-20200708' not 'tidb/br-20200708' ,but i failed.

that's just some rendering issue, it is reading from `tidb/br-20200708` as expected.

**Comment by 2983777417** [comment]
@kennytm  Thanks very much ,you're totally right .I resolve the dns resolution problem at the tikv nodes of destination cluster.
