### ISSUE TITLE
Dump and load statistics

### ISSUE THREAD

**Issue by kennytm** [pingcap/br#429]
### Describe your feature request related problem:

TiDB exposed the statistics information per table in JSON format with the `DumpStatsToJSON`/`LoadStatsFromJSON` functions. We could use these to avoid the expensive `ANALYZE TABLE` operation (which we currently don't execute at all).

### Describe the feature you'd like:

* During backup, aggregate the statistics into some `backupmeta` field (or a new file)
* During restore, recover the statistics after all SSTs are ingested.

### Describe alternatives you've considered:

* We could simply backup the entire `mysql.stats_*` tables?

### Teachability, Documentation, Adoption, Migration Strategy:

cc pingcap/tidb#18635.

**Comment by zz-jason** [comment]
> We could simply backup the entire mysql.stats_* tables?

Maybe not. The table and column id can not guarantee to be the same. @winoros @eurekaka PTAL

**Comment by siddontang** [comment]
we can support dumpling/restoring stats only in BR

**Comment by overvenus** [comment]
Can we close the issue? BR supports dump and load stat in https://github.com/pingcap/br/pull/605

**Comment by kennytm** [comment]
Duplicate of #598
