### ISSUE TITLE
Support restore data from TiCDC log

### ISSUE THREAD

**Issue by 3pointer** [pingcap/br#440]
### Describe your feature request related problem:

Part of #325 , After https://github.com/pingcap/ticdc/issues/768 TiCDC support external storage.  BR need to restore data from TiCDC output log.

### Describe the feature you'd like:

Support restore data from TiCDC log.

### Describe alternatives you've considered:

Since there are two kind of TiCDC logs KV changes and DDL events. 
For KV changes, BR  should apply log in multi-thread.

## Workload estimation(person-day)

* Design: 2
* Develop: 4
* QA: 5
* Document: 3

**Comment by kennytm** [comment]
note about merging Lightning and BR:

I oppose blindly combining the two repositories, as each has accumulated a long and diverging history. But I welcome efforts to move the KV Encoder and Local Backend to BR, and let Lightning reuse them as a library (similar to the current Split & Scatter).
