### ISSUE TITLE
How do know the BR is actual consuming time

### ISSUE THREAD

**Issue by jacktd9** [pingcap/br#478]
tidb 4.0.4  br 4.0.4
看图片 total take(s) 耗时大约 50多分钟，split region 、restore checksum 耗时远大于 total take(s) 时间 ，br 恢复开始和结束的真实耗时貌似没有计算和打印，用户侧比较关注整个恢复过程的真实时间，希望可以加下。

br restore 完成打印记录：
![image](https://user-images.githubusercontent.com/63033738/91516594-7b96ea00-e91e-11ea-88c3-436aa35578c1.png)

另：total+checksum+region split 相加所得耗时和恢复日志记录的进程实际耗时相差比较大，用来估算真实耗时貌似不准
进程实际耗时：
restorefull.log 日志第一行和最后一行时间
开始：19:02:13.528
结束：21:15:51
耗时：02:13:38

**Comment by YuJuncen** [comment]
Since #480 got merged, this problem should be resolved now. This issue yet could be closed, if more discussion needed, feel free to reopen it.
