### ISSUE TITLE
Failing to backup S3 with versioning turned on

### ISSUE THREAD

**Issue by roshanjonah** [pingcap/br#501]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
Just back up to Wasabi S3 with bucket versioning turned on

2. What did you expect to see?
To back up successfully

3. What did you see instead?
Full backup <-...............................................................................................................................................................> 0.47%
Error: msg:"Io(Custom { kind: Other, error: \"failed to put object Request ID: None Body: <?xml version=\\\"1.0\\\" encoding=\\\"UTF-8\\\"?>\\n<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>5CE7B60A8CFBDA2F</RequestId><HostId>2yuPbg9LS+ma7AAtof0UWde+H3zuNuZu2Rd4d7yePcPGJg2x2iNhUiiZEos1Nek6vSWl5WbSu235</HostId></Error>\" })" 

4. What version of BR and TiDB/TiKV/PD are you using?
br -v (latest build on 14/09/2020)
tiup cluster version v4.0.4

**Comment by 3pointer** [comment]
Could you please upload the full BR cmd or BR logs for debug?

**Comment by roshanjonah** [comment]
> Could you please upload the full BR cmd or BR logs for debug?
Attached is the backuptable.log 

> It seems irrelevant with versioning, will it back up successfully with versioning turned off?
Weirdly - yes it does seem to do it successfully but for some odd reason, now it's giving the error in the attached log. 

[backuptable.log](https://github.com/pingcap/br/files/5229072/backuptable.log)

**Comment by 3pointer** [comment]
According to this log we can see BR cannot connect to PD (`10.9.2.133:2379`) Server. please check the PD server is work.

And in this https://github.com/pingcap/br/issues/484#issuecomment-686230427 we found that TiKV doesn't support Virtual Host Style like `[s3.endpoint=http://s3.us-east-1.wasabisys.com]`, please change it to Path Style.

**Comment by roshanjonah** [comment]
Ok will investigate PD issue! 

Re path style, is this command okay? Sorry I am not familiar with concept of making it path-style as opposed to virtual host style.

/home/tidb/br/bin/br backup full --pd "10.9.0.149:2379" --storage "s3://tidb-backup/"$(date +"%d-%m-%Y")"" --s3.endpoint "http://s3.us-east-1.wasabisys.com/tidb-backup" --s3.provider "wasabi" --s3.region "us-east-1" --send-credentials-to-tikv=true --log-file backuptable.log

**Comment by roshanjonah** [comment]
@3pointer Any updates on this? Is our command okay? How do we turn it into path-style? Thanks

**Comment by kennytm** [comment]
@roshanjonah sorry, `--s3.provider wasabi` already means path-style is used by default. and there's no need to include the bucket name into the endpoint whether the addressing-style is "path" or "virtual host".  

but perhaps the endpoint needs HTTPS rather than HTTP?

```sh
/home/tidb/br/bin/br backup full \
    --pd "10.9.0.149:2379" \
    --storage "s3://tidb-backup/$(date +"%d-%m-%Y")" \
    --s3.endpoint "https://s3.us-east-1.wasabisys.com" \
    --s3.provider wasabi \
    --send-credentials-to-tikv=true \
    --log-file backuptable.log
```

also ensure that either the file `~/.aws/credentials`, or the env vars `$AWS_ACCESS_KEY_ID` and `$AWS_SECRET_ACCESS_KEY` contain the correct keys.

thanks.

**Comment by roshanjonah** [comment]
Awesome! Thank you so much. That helped :)
