### ISSUE TITLE
BR restore from GCS failed: download file failed

### ISSUE THREAD

**Issue by aylei** [pingcap/br#543]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
Restore from GCS

2. What did you expect to see?
Restore success

3. What did you see instead?
Restore failed with the following logs:

[br.log.tar.gz](https://github.com/pingcap/br/files/5298410/br.log.tar.gz)

One interesting output is `[error="rpc error: code = Unavailable desc = keepalive watchdog timeout"]`

4. What version of BR and TiDB/TiKV/PD are you using?

br v4.0.6
cluster v4.0.6

**Comment by YuJuncen** [comment]
Hi~ Could you help to do an experiment?

1. Use [this version of BR](https://bashupload.com/UgyoQ/dbyjU.with_keepalive_params)(#545).
2. Change the `grpc-keepalive-timeout` to 20s in both TiKV and TiDB.
3. Run BR with `--grpc-keepalive-timeout 20s`.

Does this issue still happen in this condition?

**Comment by shuijing198799** [comment]
It seems use this PR https://github.com/YuJuncen/br/tree/editable-keepalive to adjust keepalivetimeout 20 seconds can't fix this issue, but if I adjust it to 20m, recover successful. but the restore speed is rarely slow (about 56M/s).  And I think the root cause is still not very clean.

**Comment by YuJuncen** [comment]
#545 has a bug that causes those configs don't apply to restore at all(!). (see #567)

But adjusting keepalive timeout to 20m did works, and the string `keepalive watchdog timeout` only appears in the `grpc/grpc` library, maybe the TiKV side has some problem... (Blocking operations in gRPC handlers?)
