### ISSUE TITLE
BR won't clean up the environment when exit by SIGTERM

### ISSUE THREAD

**Issue by YuJuncen** [pingcap/br#557]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
- start BR (restore or backcup with `--remove-schedulers`)
- waiting for the progress bar present, then press <kbd>ctrl</kbd> + <kbd>c</kbd>

2. What did you expect to see?
The cluster config changed by BR should be undone, since SIGTERM allows us to gracefully stop.

3. What did you see instead?
The cluster has stuck in the config that BR has set. (For current master, PD schedulers could be reset due to #551 )
<img width="951" alt="image" src="https://user-images.githubusercontent.com/36239017/96206618-eb7b3580-0f9b-11eb-8322-7208048abee7.png">

4. What version of BR and TiDB/TiKV/PD are you using?

v4.0.7

#### Note:

We listen to signals here:

https://github.com/pingcap/br/blob/d2d5bbaf29bdbc2b1d9453ec65096e04c52b529e/main.go#L34-L39

Canceling the context could make other goroutines eventually exit and clean up, but we leave no time for them.

<del>Add a `time.Sleep(30 * time.Second)`</del> remove those `os.Exit`s could help. But there are still some problems:

https://github.com/pingcap/br/blob/d2d5bbaf29bdbc2b1d9453ec65096e04c52b529e/pkg/task/backup.go#L222-L227

We use the global context to do the cleanup tasks, which will always fail if the outer context is canceled. We should change it to a new context with a timeout, the timeout could be the same as the sleep time before stopping.

**Comment by kennytm** [comment]
maybe just remove these two `os.Exit`?

**Comment by YuJuncen** [comment]
> maybe just remove these two `os.Exit`?

Good if fully ignoring `SIGTERM` or something likewise is acceptable... 🤔

**Comment by kennytm** [comment]
> But we will always exit with 0 (and we would get a debug log a little hard to read, maybe).

You exit with non-zero when `err != nil`.
