### ISSUE TITLE
Recovery speed will slow down over time

### ISSUE THREAD

**Issue by shuijing198799** [pingcap/br#570]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
Data size : 1.4 T * 3
TiKV * 3 8 C , 52 G mem
TiDB * 2 8 C 

The speed of restore is shown below
```
I1026 14:58:31.627932       1 restore.go:87] [2020/10/26 14:58:31.627 +00:00] [INFO] [collector.go:211] ["Full restore Success summary: total restore files: 35253, total success: 35253, total failed: 0, total take(Full restore time): 5h53m12.041811489s, total take(real time): 2h58m55.456039055s, total kv: 10140081556, total size(MB): 1478230.72, **avg speed(MB/s): 69.75"]** ["split region"=4m7.244702684s] ["restore checksum"=2h58m45.894107294s] ["restore ranges"=19861] [Size=1056898804895]
```
the TiKV CPU usage is become lower except checksum.

![2020-10-26 23-10-36 的屏幕截图](https://user-images.githubusercontent.com/30903849/97190358-94b5fd00-17e0-11eb-9aa3-2696ec42a9c4.png)

the TiKV mem is keep increasing
![2020-10-26 23-10-55 的屏幕截图](https://user-images.githubusercontent.com/30903849/97190425-a4354600-17e0-11eb-87e8-b13461cf69ba.png)

and the speed is keep reducing

![2020-10-26 23-10-44 的屏幕截图](https://user-images.githubusercontent.com/30903849/97190461-b1523500-17e0-11eb-908e-9db54f02fe10.png)

2. What did you expect to see?

Find the reason and maybe improve it.

**Comment by kennytm** [comment]
we can get a pprof graph of each tikv to see what is occupying the memory? unless it is taken by rocksdb that is.

**Comment by shuijing198799** [comment]
> we can get a pprof graph of each tikv to see what is occupying the memory? unless it is taken by rocksdb that is.

It is running now, maybe finished at 18:00

**Comment by shuijing198799** [comment]
![flame0_page-0001](https://user-images.githubusercontent.com/30903849/97288203-83243200-1880-11eb-96ef-0c2e661aa859.jpg)
![flame1_page-0001](https://user-images.githubusercontent.com/30903849/97288241-8fa88a80-1880-11eb-8f30-7c8645fe9479.jpg)
![flame2_page-0001](https://user-images.githubusercontent.com/30903849/97288292-9d5e1000-1880-11eb-90d7-edfa02177cbe.jpg)
@kennytm  FYI

**Comment by shuijing198799** [comment]
/close https://github.com/tikv/tikv/pull/8865
![Uploading 2020-11-02 13-05-31 的屏幕截图.png…]()

**Comment by shuijing198799** [comment]
close https://github.com/tikv/tikv/pull/8865
![2020-11-02 13-05-31 的屏幕截图](https://user-images.githubusercontent.com/30903849/97831941-77b38980-1d0c-11eb-995d-53b5c31c24d1.png)
