### ISSUE TITLE
Backup workers names are the same leads to indistinguishable CPU usage in grafan dashboard

### ISSUE THREAD

**Issue by overvenus** [pingcap/br#585]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

Run backup.

2. What did you expect to see?

Distinguishable CPU usage in grafana backup/restore dashboard.

This is cause backup worker threads use the same name "backup-worker" .

https://github.com/tikv/tikv/blob/5f7744942e61946f942148efb0b60389a37b6fa9/components/backup/src/endpoint.rs#L505-L507

3. What did you see instead?

Indistinguishable CPU usage in grafana backup/restore dashboard.

4. What version of BR and TiDB/TiKV/PD are you using?

v4.0.7 TiKV/BR

**Comment by 3pointer** [comment]
this PR fixed the issue https://github.com/tikv/tikv/pull/8974
