### ISSUE TITLE
Analyze database after restore

### ISSUE THREAD

**Issue by overvenus** [pingcap/br#598]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

After restoring a database, TiDB may choose a wrong plan for selects.

2. What did you expect to see?

After restoring a database, BR should issue an analysis automatically or restore analysis data too.

**Comment by kennytm** [comment]
Backing up the stats via `:10080/stats/dump` and restoring them with `LOAD STATS` (not through SQL, for sure) sounds more appropriate for BR.

**Comment by overvenus** [comment]
BR embeds a TiDB, so it should be able to get `:10080/stats/dump` somehow without making an HTTP request. Also there is one thing we should notice that stats data binds to table ID, we need the change the table ID after restore.

eg, table `mysql.stats_meta`

```mysql
MySQL [mysql]> select * from stats_meta;
+--------------------+----------+--------------+-------+
| version            | table_id | modify_count | count |
+--------------------+----------+--------------+-------+
| 420879943098957839 |       47 |        15830 |   100 |
| 420879943098957826 |       49 |        10276 |   100 |
| 420879929664339972 |       51 |            0 |     0 |
+--------------------+----------+--------------+-------+
3 rows in set (0.001 sec)
```

**Comment by kennytm** [comment]
`/stats/dump/{db}/{table}/{snapshot}` uses [`DumpStatsToJSON`](https://github.com/pingcap/tidb/blob/e136429d8dc5d70f43cd3f94179b0b9f47595097/statistics/handle/dump.go#L116) and `LOAD STATS` uses [`LoadStstsFromJSON`](https://github.com/pingcap/tidb/blob/e136429d8dc5d70f43cd3f94179b0b9f47595097/statistics/handle/dump.go#L174), both of which uses the JSONTable type which are TableID-independent.
