### ISSUE TITLE
Treat (+) specially in storage url query.

### ISSUE THREAD

**Issue by 3pointer** [pingcap/br#603]
### Describe your feature request related problem:

we use url query to pass some parameters to storage config. but in s3 storage, secret_access_key may contains `+` usually.
the `+` character has a special meaning in a url, If we want to use the `+` sign we need to URL encode it by change `+` to `%2B`.
### Describe the feature you'd like:

we should do the transform internally.

**Comment by overvenus** [comment]
Regex for AWS S3 access key and private key

> Search for access key IDs: (?<![A-Z0-9])[A-Z0-9]{20}(?![A-Z0-9]).  In English, this regular expression says: Find me 20-character, uppercase, alphanumeric strings that don’t have any uppercase, alphanumeric characters immediately before or after.
> Search for secret access keys: (?<![A-Za-z0-9/+=])[A-Za-z0-9/+=]{40}(?![A-Za-z0-9/+=]).  In English, this regular expression says: Find me 40-character, base-64 strings that don’t have any base 64 characters immediately before or after.


See https://aws.amazon.com/blogs/security/a-safer-way-to-distribute-aws-credentials-to-ec2/#:~:text=Finding%20hard-coded%20credentials%20in%20your%20code

**Comment by kennytm** [comment]
Performing `ReplaceAll(_, "+", "%2B")` before `url.Parse` should be sufficient.
