### ISSUE TITLE
Possible panic when restore a backup that enables cross table merge.

### ISSUE THREAD

**Issue by overvenus** [pingcap/br#608]
PD can merge regions that belong to different tables. It is possible that a region's start key and end key have different table IDs. And it breaks BR restore's prerequisite. BR needs to be able to restore such regions.

https://github.com/pingcap/br/blob/bb4294d81939fc13ca7e0f848dcbb18526b9493e/pkg/restore/util.go#L200-L207

Cc https://github.com/tikv/pd/pull/3129

**Comment by 3pointer** [comment]
even PD can merge two table in same the region, BR will backup two tables separately due to `BackupRanges`, so the each  SST file will only contain one tableID.

**Comment by overvenus** [comment]
Right, thanks!
