### ISSUE TITLE
restore rpc timeout is right?

### ISSUE THREAD

**Issue by CadmusJiang** [pingcap/br#650]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
There are three tikv in tidb cluster. We add network chaos between restore pod and tikv-0. When I recover data from S3 to tikv, rpc timeout appeared.
![image](https://user-images.githubusercontent.com/59600278/102213464-bba3cc00-3f11-11eb-86ef-4d5af87c0e9e.png)

2. What did you expect to see?
Restore is  successful, data can be transfered from tikv1/tikv2 to tikv0

3. What did you see instead?

4. What version of BR and TiDB/TiKV/PD are you using?
br - release-4.0-nightly
tikv-server -v 4.0.7 Git Commit Hash:   bc0a9b3974f32cc2e08244a6eaf5284e5e5f4d76

**Comment by 3pointer** [comment]
if there has network problem between `restore pod` and `tikv-0`. then restore cannot succeed by design.
