### ISSUE TITLE
refactor storage.ExternalStorage interface

### ISSUE THREAD

**Issue by lichunzhu** [pingcap/br#651]
### Describe your feature request related problem:

Currently, `ExternalStorage`'s logic has some problems:
1. `ExternalStorage.Write` and `ExternalStorage.Read` are hardly used. In most situations, we need streaming write & read.
2. It's hard to use `multi-uploader` now. We need to do these things to open a `UploderWriter`:
  a. Create a new `ExternalStorage`.
  b. Create a new `Uploader` through `ExternalStorage.CreateUploader`.
  c. Create a new `Writer` though `NewUploaderWriter`. Then use `Writer.Write` and `Writer.Close` to upload.
3. The concept of `ExternalStorage.Write` and `Writer.Write` are confusing. Users need to read our code to know what do they do.
4. It's hard to add the compress option in the future.

### Describe the feature you'd like:

Delete `Uploader`, `Writer`, refactor `ExternalStorage` and add interface `ExternalFile`.

```go
type ExternalStorage interface {
        // Equal to original ExternalStorage.Write, similar to ioutil.WriteFile
	WriteFile(ctx context.Context, name string, data []byte) error
        // Equal to original ExternalStorage.Read, similar to ioutil.ReadFile
	ReadFile(ctx context.Context, name string) ([]byte, error)
	FileExists(ctx context.Context, name string) (bool, error)
        // Open a file reader
	Open(ctx context.Context, path string) (ExternalFileReader, error)
        // Open a file writer
        Create(ctx context.Context, path string) (ExternalFileWriter, error)
	WalkDir(ctx context.Context, opt *WalkOption, fn func(path string, size int64) error) error
	URI() string
}

// Streaming external file reader
type ExternalFileReader interface {
        io.Reader
        io.Seeker
        io.Closer
}

// Streaming external file writer
type ExternalFileWriter interface {
        io.WriteCloser
}

type withCompression struct {
        inner ExternalStorage
        compressionType CompressionType
}

func WithCompression(inner ExternalStorage, compressionType CompressionType) ExternalStorage {
    return &withCompression{inner: inner, compressionType: compressionType}
}
```

### Describe alternatives you've considered:

None

### Teachability, Documentation, Adoption, Migration Strategy:

None

**Comment by kennytm** [comment]
`WithCompress` shouldn't be a method of `ExternalStorage`

**Comment by lichunzhu** [comment]
> `WithCompress` shouldn't be a method of `ExternalStorage`

Should we set `compress` type when we create `ExternalStorage`?

**Comment by kennytm** [comment]
No it should be a free function which wraps an existing ExternalStorage with compression. Implementation of ExternalStorage for S3/GCS/Local/Noop should not need to care about compression.

```go
func WithCompression(inner ExternalStorage, compressionType CompressionType) ExternalStorage {
    return &withCompression{inner: inner, compressionTypr: compressionType}
}
```

**Comment by lichunzhu** [comment]
> No it should be a free function which wraps an existing ExternalStorage with compression. Implementation of ExternalStorage for S3/GCS/Local/Noop should not need to care about compression.
> 
> ```go
> func WithCompression(inner ExternalStorage, compressionType CompressionType) ExternalStorage {
>     return &withCompression{inner: inner, compressionTypr: compressionType}
> }
> ```

Gotta. Already updated in the issue description. Is there any more problem?

**Comment by kennytm** [comment]
The `WithCompression` *method* within `ExternalStorage` should still be removed.

I'm also not so sure about `ExternalFile` implementing both `Reader` and `Writer`.

**Comment by lichunzhu** [comment]
> The `WithCompression` _method_ within `ExternalStorage` should still be removed.
> 
> I'm also not so sure about `Open` and `Create` sharing `ExternalFile`, causing it implementing both `Reader` and `Writer`.

Updated. I think it over again and separate `ExternalFile` to `ExternalFileReader` and `ExternalFileWriter`.

**Comment by kennytm** [comment]
Ok. Except that `ExternalFileWriter` is equivalent to `io.WriteCloser` 🤣
