### ISSUE TITLE
Failed to increment restore when already restored in the past

### ISSUE THREAD

**Issue by longfangsong** [pingcap/br#663]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
    1. first start a TiDB cluster with `tiup`
        ```bash
        tiup playground
        ```
    2. create some test data in mysql promote
        ```bash
        mysql --host 127.0.0.1 --port 4000 -u root
        ```
        ```mysql
        create table t(id int);
        insert into t(id) values (1), (2);
        ```
    3. backup once with br
        ```bash
        tiup br backup full --pd localhost:2379 -s "local:///tmp/backup/"
        ```
     4. restore at once
         ```bash
         tiup br restore full --pd localhost:2379 -s "local:///tmp/backup"
         ```
      5. create more test data
          ```bash
          mysql --host 127.0.0.1 --port 4000 -u root
          ```
          ```mysql
          insert into t(id) values (3);
          ```
     6. increment backup
         ```bash
         <<< tiup br validate decode --field="end-version" -s local:///tmp/backup/
         >>> 421824803438592001
         <<< tiup br backup full --pd localhost:2379 -s "local:///tmp/backup/incr" --lastbackupts 421824803438592001
         ```
     7. full restore
         ```bash
         tiup br restore full --pd localhost:2379 -s "local:///tmp/backup"
         ```

2. What did you expect to see?
   Run successful.

3. What did you see instead?
    ```bash
    Error: failed to validate checksum: [BR:Restore:ErrRestoreChecksumMismatch]restore checksum mismatch
    ```

4. What version of BR and TiDB/TiKV/PD are you using?
   BR/TiDB/TiKV/PD: `v4.0.9`, with tiup

**Comment by longfangsong** [comment]
The same problem also affect backuping/restoring with `BACKUP` statement in SQL.

It is even worse there because it just corrupt the data instead of return an error.

**Comment by 3pointer** [comment]
> Please answer these questions before submitting your issue. Thanks!
> 
> 1. What did you do?
>    
>    1. first start a TiDB cluster with `tiup`
>       ```shell
>       tiup playground
>       ```
>    2. create some test data in mysql promote
>       ```shell
>       mysql --host 127.0.0.1 --port 4000 -u root
>       ```
>       
>       
>       ```sql
>       create table t(id int);
>       insert into t(id) values (1), (2);
>       ```
>    3. backup once with br
>       ```shell
>       tiup br backup full --pd localhost:2379 -s "local:///tmp/backup/"
>       ```
>    4. restore at once
>       ```shell
>       tiup br restore full --pd localhost:2379 -s "local:///tmp/backup"
>       ```
>    5. create more test data
>       ```shell
>       mysql --host 127.0.0.1 --port 4000 -u root
>       ```
>       
>       
>       ```sql
>       insert into t(id) values (3);
>       ```
>    6. increment backup
>       ```shell
>       <<< tiup br validate decode --field="end-version" -s local:///tmp/backup/
>       >>> 421824803438592001
>       <<< tiup br backup full --pd localhost:2379 -s "local:///tmp/backup/incr" --lastbackupts 421824803438592001
>       ```
>    7. full restore
>       ```shell
>       tiup br restore full --pd localhost:2379 -s "local:///tmp/backup"
>       ```
> 2. What did you expect to see?
>    Run successful.
> 3. What did you see instead?
>    ```shell
>    Error: failed to validate checksum: [BR:Restore:ErrRestoreChecksumMismatch]restore checksum mismatch
>    ```
> 4. What version of BR and TiDB/TiKV/PD are you using?
>    BR/TiDB/TiKV/PD: `v4.0.9`, with tiup

It's worked as expected. because you insert some data into table before `vii. full restore`

**Comment by longfangsong** [comment]
> It's worked as expected. because you insert some data into table before `vii. full restore`

Then what about using the SQL to do the backup/restore? Should we return an error instead of left the data corrupted?
