### ISSUE TITLE
Backup results explanation more details

### ISSUE THREAD

**Issue by superlzs0476** [pingcap/br#707]
### Describe your feature request related problem:

https://docs.pingcap.com/tidb/stable/backup-and-restore-use-cases#backup-results-explanation

We want to know about other parameters explain details. Such as these.
[“backup checksum”=1m33.986578011s] 
[“backup fast checksum”=19.09283ms] 
[“backup total regions”=3958] 
[Size=51335332546] 
[BackupTS=422211224595857430]

**Comment by kennytm** [comment]
can you elaborate? or is it a documentation request?

**Comment by overvenus** [comment]
@lichunzhu has add the explanation in https://github.com/pingcap/docs-cn/pull/5450
