### ISSUE TITLE
Backup cause TiKV OOM with too large regions

### ISSUE THREAD

**Issue by tennix** [pingcap/br#751]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

We restored a cluster from backup with TiKV/TiDB using GCP n1-standard-1 instance type.

The first time it failed in 6 minutes, the second time we tried the restore failed after 1 hour and a half. So parts of the data is restored. These two failures seemed to caused by network errors between tikv and tidb.

Then we split the restore by tables, two large tables restored separately after the small tables restored. With these steps, the whole restoration succeeded.

After that, we did fully backup during low peak traffic, but the backup failed due to TiKV OOM

2. What did you expect to see?

The full backup succeed

3. What did you see instead?

The full backup failed due to TiKV OOM

4. What version of BR and TiDB/TiKV/PD are you using?

BR version GitHash is 804aa908719748888010edaa944757b82f99f4df
Other cluster components are v4.0.9.

5. Operation logs
   - Please upload `br.log` for BR if possible
   - Please upload `tidb-lightning.log` for TiDB-Lightning if possible
   - Please upload `tikv-importer.log` from TiKV-Importer if possible
   - Other interesting logs

6. Configuration of the cluster and the task
   - `tidb-lightning.toml` for TiDB-Lightning if possible
   - `tikv-importer.toml` for TiKV-Importer if possible
   - `topology.yml` if deployed by TiUP
The backup command is:
```
br backup full --pd=db-pd.my-cluster:2379 --ca=/var/lib/cluster-client-tls/ca.crt --cert=/var/lib/cluster-client-tls/tls.crt --key=/var/lib/cluster-client-tls/tls.key --status-addr=0.0.0.0:8089 --send-credentials-to-tikv=true --storage=gcs://my-bucket/my-directory/ --concurrency=32
```
7. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus if possible
<img width="757" alt="image" src="https://user-images.githubusercontent.com/7932127/108986974-b57a5a80-76cd-11eb-909e-447d22d1863f.png">

We've finally found that there are some very big regions which causes the TiKV OOM during backup. The largest region is about 6GB.

**Comment by overvenus** [comment]
The OOM issue is fixed in https://github.com/tikv/tikv/pull/9283, and will be released in v4.0.11.
