### ISSUE TITLE
Support KV-only mode

### ISSUE THREAD

**Issue by andylokandy** [pingcap/br#764]
## Feature Request

Currently, `tidb-lightning` only supports SQL-like data to be imported into TiKV. But, in fact, `tidb-lightning` consists of two parts: translating SQL data in KV pairs and importing KV pairs into TiKV. By splitting these two steps, we can support importing KV-like data into TiKV, e.g. migrating from HBASE to TiKV.

**Comment by andylokandy** [comment]
@kennytm I'd like to propose it to be a GSoC project, would you like to be the mentor?

**Comment by kennytm** [comment]
I think you need to specify how the split-up Lightning will work with the HBase backup.

(BTW if you just could produce sorted KV pairs (or even an SST file), you could directly use TiKV's [`sst_importer`](https://github.com/pingcap/kvproto/blob/3cd2fc5fad226caeffed72297e3e13a571f5592e/proto/import_sstpb.proto#L34) service without needing Lightning or BR.)

**Comment by andylokandy** [comment]
> BTW if you just could produce sorted KV pairs (or even an SST file), you could directly use TiKV's sst_importer service without needing Lightning or BR.

This indeed works, but only if `Lightning` and the `KV import tool` depends on the same component we can guarantee that they are both well-maintained.

**Comment by andylokandy** [comment]
I'm sorry. I might miss https://github.com/tikv/importer. Is it GA?

**Comment by kennytm** [comment]
Yes but this has been passively-maintained since 4.0. It lacks some optimizations we've added to Lightning Local Backend (e.g. batched region splitting).

**Comment by sudo-sturbia** [comment]
Hi! I'm interested in working on this as a part of GSoC. I'd appreciate it if you can point me to where i can start (maybe smaller lightning-related issues) to get a better understanding of how things work.

**Comment by HuGanghui** [comment]
Hi, I am also interested in this feature. And considering we already have https://github.com/tikv/importer but it has been passively-maintained since 4.0, so we still need to split these two steps in tidb-lightning and support KV-only mode, right?

**Comment by andylokandy** [comment]
@sudo-sturbia It's glad to hear you're interested in the GSoC program! I think the program is still in the process of project selection, so just wait for the GSoC official announcement.

**Comment by andylokandy** [comment]
@HuGanghui We do have https://github.com/tikv/importer. But we're going to re-use the codebase from Lightning to better maintain the import tool for both TiDB and TiKV. Besides. I think in the GSoC program, an HBase migration tool is a good-to-have example that shows how to use the KV importer.

**Comment by HuGanghui** [comment]
@andylokandy I wonder if the project required not only a knowledge of Go, but also Rust, and if so, was it enough to be able to read Rust, or to be able to write Rust?

**Comment by andylokandy** [comment]
Rust ability is required because the mentee may need to read through `https://github.com/tikv/importer`.

**Comment by kennytm** [comment]
The entire importer has been rewritten in Go as the "local backend", so reading `tikv/importer` is not necessary. However, it is still recommended as TiKV itself is written in Rust, which you may need to understand for debugging.

**Comment by HuGanghui** [comment]
@kennytm I know from the Lighting [tidb-lightning-overview](documentationhttps://docs.pingcap.com/tidb/stable/tidb-lightning-overview) and [tidb-lightning-overview-zh](https://docs.pingcap.com/zh/tidb/stable/tidb-lightning-overview) so far Lighting support Import the data source in Dumpling, CSV, or Amazon Aurora Parquet output format. And Now we want to let Lighting support RawKV mode int this issue right? And now Lighting have Importer-backend、Local-backend and TiDB-backend, In this issue, we just need to consider support RawKV mode on Local-backend right?

**Comment by kennytm** [comment]
@HuGanghui yes it's local backend only. In fact, this feature doesn't need to be sharing the same architecture as `tidb-lightning` proper.

**Comment by glorv** [comment]
@Little-Wallace is currently working on a similar feature.

**Comment by Little-Wallace** [comment]
Yeah. There is proto and method which will be supported in TiKV: https://github.com/pingcap/kvproto/pull/743

**Comment by andylokandy** [comment]
This issue is tracked by https://github.com/tikv/tikv/issues/9778
