### ISSUE TITLE
Test br_table_partition fails

### ISSUE THREAD

**Issue by overvenus** [pingcap/br#783]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```
[2021-03-03T06:35:27.284Z] ERROR 1146 (42S02) at line 1: Table 'br_table_partition.usertable_List' doesn't exist
```

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/5132/pipeline#step-891-log-340

**Comment by YuJuncen** [comment]
`[2021-03-03T06:35:11.489Z] ERROR 1193 (HY000) at line 1: Unknown system variable 'tidb_enable_list_partition'`

**Comment by 3pointer** [comment]
@glorv lightning met this error a few days ago...

**Comment by glorv** [comment]
This is because the corresponding pr https://github.com/pingcap/tidb/pull/22909 at commit `789d775` is too old and not merge the newest tidb master that it doesn't not this new variable.

**Comment by overvenus** [comment]
Other failed tests:

- https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/5308/pipeline#step-822-log-330

**Comment by overvenus** [comment]
> This is because the corresponding pr [pingcap/tidb#22909](https://github.com/pingcap/tidb/pull/22909) at commit `789d775` is too old and not merge the newest tidb master so it doesn't support this new variable.
> 
> So I think this issue can be closed. @overvenus @3pointer

Agree, closed!
