### ISSUE TITLE
Check important environment variables 

### ISSUE THREAD

**Issue by overvenus** [pingcap/br#810]
1. What did you do?
If possible, provide a recipe for reproducing the error.

Some important environment variables  affects BR and TiDB-Lightning, eg. http_proxy which may break gRPC connection.

The following link is how TiKV checks environment variables, we can do the same.

https://github.com/tikv/tikv/blob/2cee812f236e3134c9df8b37e73ac51a5f90690f/components/tikv_util/src/lib.rs#L509

**Comment by glorv** [comment]
Lighting has do log `http_proxy` at https://github.com/pingcap/br/blob/32cc80956ac922b01944eb5b40ac0b0f85bb8015/pkg/lightning/lightning.go#L329-L335

**Comment by overvenus** [comment]
Can we close the issue? Is there any missing envs?

**Comment by YuJuncen** [comment]
Seems not, if any, we can reopen this, anyway.
