### ISSUE TITLE
`BuildBackupRangeAndSchema` leaks memory

### ISSUE THREAD

**Issue by overvenus** [pingcap/br#818]
1. What did you do?
If possible, provide a recipe for reproducing the error.

BR backup holds too much memory if a cluster has many tables.

We take heap profile during backup, they show `BuildBackupRangeAndSchema` always hold 570MB memory even if the function returned already.

https://gist.github.com/overvenus/4491e987dca672fd62705d29bb254d03

2. What did you expect to see?

`BuildBackupRangeAndSchema` should not leak, and it's memory consumption should be O(1) not O(n) (n is a number of tables). 

3. What did you see instead?

BR consumes too much memory.

**Comment by overvenus** [comment]
From heap profile, we find one major `in_use` memory is created by 

https://github.com/pingcap/br/blob/facb28a4e57d93c166ce5939a3c22db5615fbfab/pkg/backup/client.go#L355

```
                                          540.22MB   100% |   github.com/pingcap/br/pkg/backup.BuildBackupRangeAndSchema pkg/backup/client.go:355
  540.22MB 35.59% 35.59%   540.22MB 35.59%                | encoding/json.Marshal encoding/json/encode.go:165
----------------------------------------------------------+-------------
```

It shows the memory is hold by lots of `tableData`, they are the byte representation of table info and loaded before starting backup job at once. Memory can be reduced by loading them lazily.

**Comment by overvenus** [comment]
Reproduced the issue with 40K tables, generated by GO-YCSB

```bash
for i in $(seq 1 40000); do { go-ycsb load mysql -p workload=core -p mysql.host=xxx -p mysql.port=xxx -p mysql.user=root -p recordcount=20 -p fieldcount=40 -p fieldlength=16 -p threadcount=4 -p table=usertable$i; } done;
```

Add a log to BR, and it shows that `tableData` holds about  460.6MB memory.
<details> <summary> Diff </summary>

```diff
diff --git a/pkg/backup/client.go b/pkg/backup/client.go
index d6043042..fddef0a6 100644
--- a/pkg/backup/client.go
+++ b/pkg/backup/client.go
@@ -394,6 +394,7 @@ func BuildBackupRangeAndSchema(
                log.Info("nothing to backup")
                return nil, nil, nil
        }
+       log.Info("backup schemas size", zap.Int("size", backupSchemas.size()))
        return ranges, backupSchemas, nil
 }
 
diff --git a/pkg/backup/schema.go b/pkg/backup/schema.go
index 1714a506..97d6a1f2 100644
--- a/pkg/backup/schema.go
+++ b/pkg/backup/schema.go
@@ -46,6 +46,16 @@ func newBackupSchemas() *Schemas {
        }
 }
 
+func (pending *Schemas) size() int {
+       sum := 0
+       for k, v := range pending.schemas {
+               sum += len([]byte(k))
+               sum += len(v.Db)
+               sum += len(v.Table)
+       }
+       return sum
+}
+
 func (pending *Schemas) pushPending(
        schema backup.Schema,
        dbName, tableName string,
```

</details>

**Comment by tiancaiamao** [comment]
Is this one related? https://github.com/pingcap/tidb/issues/18048

**Comment by overvenus** [comment]
> Is this one related? [pingcap/tidb#18048](https://github.com/pingcap/tidb/issues/18048)

Maybe related, as the memory is allocated from Domain. For this issue, the main point is that Domain caches table info too aggressive, one table info may be large than 10KB. We can expect table info to occupy GB+ memory if there are many tables.
