### ISSUE TITLE
backup and recovery  rawkv requests specifying the startkey and endkey manually.

### ISSUE THREAD

**Issue by yuzhibotao** [pingcap/br#849]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
backup rawkv using br must specify startkey and endkey manually.

2. What did you expect to see?
I want to remove startkey and endkey  in command to backup all data in rawkv.

3. What did you see instead?

4. What version of BR and TiDB/TiKV/PD are you using?
v4.0.10

5. Operation logs
   - Please upload `br.log` for BR if possible
   - Please upload `tidb-lightning.log` for TiDB-Lightning if possible
   - Please upload `tikv-importer.log` from TiKV-Importer if possible
   - Other interesting logs

6. Configuration of the cluster and the task
   - `tidb-lightning.toml` for TiDB-Lightning if possible
   - `tikv-importer.toml` for TiKV-Importer if possible
   - `topology.yml` if deployed by TiUP

7. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus if possible

**Comment by YuJuncen** [comment]
If possible, could you help to test whether `--start-key "" --end-key ""` works?

**Comment by YuJuncen** [comment]
After a short testing, seems it would be OK to pass empty string directly. (Even we need to modify BR to bypass some tests.)

A PR can be provided soon.

<details>
<summary>
Test script:
</summary>
test_full_rawkv() {
    check_range_start=00
    check_range_end=ff

    checksum_full=$(checksum $check_range_start $check_range_end)
    # backup current state of key-values
    run_br --pd $PD_ADDR backup raw -s "local://$TEST_DIR/rawkv-full" --format raw

    clean $check_range_start $check_range_end
    # Ensure the data is deleted
    checksum_new=$(checksum $check_range_start $check_range_end)
    if [ "$checksum_new" == "$checksum_full" ];then
        echo "failed to delete data in range"
        fail_and_exit
    fi

    run_br --pd $PD_ADDR restore raw -s "local://$TEST_DIR/rawkv-full" --format raw
    checksum_new=$(checksum $check_range_start $check_range_end)
    if [ "$checksum_new" != "$checksum_full" ];then
        echo "failed to restore"
        fail_and_exit
    fi
}
</details>
