### ISSUE TITLE
br  can not  backup and resotore tidb   system databases  like mysql.user

### ISSUE THREAD

**Issue by wangbinhe3db** [pingcap/br#872]
## Question
i want to backup and restore all tidb data ,  but  br can not   backup and resotore tidb system databases 
and i see this in code 
![image](https://user-images.githubusercontent.com/78577992/111099647-ea692700-8580-11eb-9367-e6dd3b98bda0.png)
br  can not  backup and restore tidb   system databases  like mysql.user
i want to know the reason ?

**Comment by wangbinhe3db** [comment]
\cc  @kennytm

**Comment by kennytm** [comment]
@wangbinhe3db we explicitly opt out of system tables. Because if the user wrongly restore on a cluster with different schema version, BR can easily brick the entire cluster. See #679 for the intended direction how we'd like to handle system tables.

**Comment by SunRunAway** [comment]
1. `mysql.user` may have the account information which customer may forget in their brain.
2. TiDB allow a customer to create a table in the `mysql` schema.

I suggest we should backup the system tables, and can opt out when restoring.

@kennytm @IANTHEREAL

**Comment by kennytm** [comment]
@SunRunAway please discuss the plan about system tables in #679. i'm closing this issue as duplicate.
