### ISSUE TITLE
Unit test failed

### ISSUE THREAD

**Issue by 3pointer** [pingcap/br#911]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
``` [util.go:316] ["table ids mismatch"] [startID=1] [endID=2] [file="{name=file_write.sst,CF=sha256=startKey=748000000000000001,endKey=748000000000000002,startVersion=0,endVersion=0,totalKvs=0,totalBytes=0,CRC64Xor=0}"] ```

2. What did you expect to see?
test passed

3. What did you see instead?

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/6268/pipeline

**Comment by YuJuncen** [comment]
```
 value *errors.withStack = listen tcp 0.0.0.0:16149: bind: address already in use ("listen tcp 0.0.0.0:16149: bind: address already in use")
```

But why the port is already in use?
