### ISSUE TITLE
LightningServerSuite.TestRunServer test failed.

### ISSUE THREAD

**Issue by 3pointer** [pingcap/br#912]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
FAIL: lightning_test.go:129: lightningServerSuite.TestRunServer
[2021-03-15T10:56:23.708Z] lightning_test.go:192:
[2021-03-15T10:56:23.708Z]     c.Fatalf("task is not queued after 500ms (i = %d)", i)
[2021-03-15T10:56:23.708Z] ... Error: task is not queued after 500ms (i = 4)
```

2. What did you expect to see?

test passed.

3. What did you see instead?

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/6335/pipeline

**Comment by sleepymole** [comment]
It can't be reproduced now.
