### ISSUE TITLE
Test br_full_ddl failed.

### ISSUE THREAD

**Issue by 3pointer** [pingcap/br#913]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
backup stats are not equal.

2. What did you expect to see?
test passed.

3. What did you see instead?
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/6351/pipeline

**Comment by YuJuncen** [comment]
Has this been fixed by https://github.com/pingcap/br/pull/888?
