### ISSUE TITLE
Test lightning_disk_quota faild.

### ISSUE THREAD

**Issue by 3pointer** [pingcap/br#914]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```[2021-03-16T09:25:15.960Z] tidb lightning encountered error:  checksum mismatched remote vs local => (checksum: 6662380652007003920 vs 16889754522338585276) (total_kvs: 3867 vs 4000) (total_bytes:1400611257 vs 1500381872)```

2. What did you expect to see?
test passed.

3. What did you see instead?

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/6406/pipeline/86

**Comment by sleepymole** [comment]
It can't be reproduced now.
