### ISSUE TITLE
Test lightning_checkpoint failed

### ISSUE THREAD

**Issue by 3pointer** [pingcap/br#915]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
TEST FAILED: OUTPUT DOES NOT CONTAIN 's: 22950450'

2. What did you expect to see?
test passed.

3. What did you see instead?

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/6490/pipeline

**Comment by overvenus** [comment]
Other failed tests:
- https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/7787/pipeline#step-715-log-407

**Comment by glorv** [comment]
closed by #1006
