### ISSUE TITLE
Test lightning_disk_quota failed: hard disk quota exceeded, actual size = 712744960

### ISSUE THREAD

**Issue by 3pointer** [pingcap/br#916]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
raise error `[2021-03-18T10:08:12.747Z] hard disk quota exceeded, actual size = 712744960`

2. What did you expect to see?
test passed.

3. What did you see instead?
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/6714/pipeline/

**Comment by sleepymole** [comment]
It can't be reproduced now.
