### ISSUE TITLE
Test lightning_checkpoint failed: Lock wait timeout exceeded

### ISSUE THREAD

**Issue by 3pointer** [pingcap/br#917]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```[2021-03-18T03:12:32.889Z] tidb lightning encountered error:  insert checkpoints failed: Error 1205: Lock wait timeout exceeded; try restarting transaction```

2. What did you expect to see?

test passed.

3. What did you see instead?

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/6613/pipeline/

**Comment by sleepymole** [comment]
It can't be reproduced now.
