### ISSUE TITLE
About building BR through make 

### ISSUE THREAD

**Issue by HuGanghui** [pingcap/br#921]
## Question

Hi, I am new to BR, when I try to use `make` command to build br in my Mac terminal, the make program does not end as the following picture:

<img width="808" alt="image" src="https://user-images.githubusercontent.com/50866227/112270465-ae3a7280-8cb4-11eb-83ab-ef418e41c212.png">

I want to know this situation is normal or is an issue. Thanks.

**Comment by kennytm** [comment]
Hi. Looks like macOS's `grep` is slightly different from Linux's version 😅. We'll check why later.

If you just need to build BR the executable, you could run `make br` instead.

**Comment by kennytm** [comment]
should have been fixed by #938.
