### ISSUE TITLE
Too many empty regions during br-restore

### ISSUE THREAD

**Issue by cosven** [pingcap/br#964]
## Question

TiDB version is v4.0.11.

### 1. Restoring 2T tpcc data with 3pd 2db 4kv.

The br version is v4.0.11.

First time
![image](https://user-images.githubusercontent.com/4962134/112918236-0222dc80-9137-11eb-89b9-ec7d2068f412.png)

Second time
![image](https://user-images.githubusercontent.com/4962134/112917742-e539d980-9135-11eb-9e21-2005d649d754.png)

### 2. Restoring 2T tpcc data with 1pd 1db 3kv. 

The br version is v4.0.12(14d55a7a3696a37e6e7f199f75c5dc405383c547)

Restore finished at 22:47:31.
![image](https://user-images.githubusercontent.com/4962134/112917592-8ecc9b00-9135-11eb-9c35-b33644435f73.png)

### 3. Restoring 2T tpcc data with 1pd 1db 3kv. 

The tikv config is 
```
coprocessor.region-split-size: "48M"
```

The br version is v4.0.11
Restore finished at 03:11:30.
![image](https://user-images.githubusercontent.com/4962134/112917328-fdf5bf80-9134-11eb-81c4-43cbf1db3998.png)

**Comment by cosven** [comment]
Re-run the first scene (3pd 2db 4kv + br v4.0.11 2t).

**Note**: I run the `go-tpc tpcc run` right after br-restore finished. I dont know if it affects the test result. 
I think I also run the `go-tpc tpcc run` in the first scene, so I update the metrics screenshot for the first scene.


![image](https://user-images.githubusercontent.com/4962134/112952035-9fe5ce00-916e-11eb-8d7e-636264d39b58.png)
![image](https://user-images.githubusercontent.com/4962134/112952074-abd19000-916e-11eb-98af-77842dc17cda.png)

**Comment by YuJuncen** [comment]
After #9924, this problem is mainly solved:
![Uploading image.png…]()

**Comment by cosven** [comment]
> Is there anything bad happened yet because of this?

Currently, no.

I think too many empty region has potential influence on tikv CPU and pd scheduling.
