### ISSUE TITLE
Lightning: stuck after runs out disk space

### ISSUE THREAD

**Issue by cyliu0** [pingcap/br#977]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
Limit the local sortkv dir filesystem size to 200M. Import 1GB tpcc data.

2. What did you expect to see?
Lightning failed and exit

3. What did you see instead?
Lightning stuck

4. What version of BR and TiDB/TiKV/PD are you using?

release-5.0

5. Operation logs
   - Please upload `br.log` for BR if possible
   - Please upload `tidb-lightning.log` for TiDB-Lightning if possible
   - Please upload `tikv-importer.log` from TiKV-Importer if possible
   - Other interesting logs

6. Configuration of the cluster and the task
   - `tidb-lightning.toml` for TiDB-Lightning if possible
   - `tikv-importer.toml` for TiKV-Importer if possible
   - `topology.yml` if deployed by TiUP

7. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus if possible

**Comment by glorv** [comment]
I think this issue should also be fixed by #753

**Comment by glorv** [comment]
closed as #753 is merged.
